# 5 - Analyses statistiques

In [1]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

In [2]:
df = pd.read_csv(
    "../data/interim/df_regroup_repu_absolu.csv", low_memory=False, dtype={"ID_orateur": str}
)

In [3]:
import datetime
import locale

# Active la locale française
locale.setlocale(locale.LC_TIME, "fr_FR.UTF-8")

'fr_FR.UTF-8'

In [4]:
df["dateSeance_ts"] = pd.to_datetime(df["dateSeanceJour"], format="%A %d %B %Y")
df["dateSeance_day"] = df["dateSeance_ts"].dt.normalize()

## Analyses générales

### Par an

In [ ]:
# Regrouper les occurrences par année
df_yearly = df.resample("YE", on="dateSeance_day").size().reset_index()
df_yearly["dateSeance_day"] = df_yearly["dateSeance_day"].dt.year  # garder juste l'année

# Tracer le graphique
fig_time = px.bar(
    df_yearly,
    x="dateSeance_day",
    y=0,
    title="Évolution annuelle de l'investissement en valeur absolue de la famille du mot 'République' (B)",
    labels={"dateSeance_day": "Année", "0": "Occurrences"},
    template="plotly_white",
)

fig_time.update_layout(showlegend=False)  # masquer la légende

fig_time.show()
df_yearly

   dateSeance_day     0
0            2017   892
1            2018  2215
2            2019  1569
3            2020  1317
4            2021  2148
5            2022   975
6            2023  1621
7            2024   692

### Par mois

In [14]:
# aficher les 10 mois les plus fréquentes sous forme de tableau
table = (
    df.resample("ME", on="dateSeance_day")
      .size()
      .sort_values(ascending=False)
      .head(50)
      .reset_index()
      .rename(columns={0: "Nombre de mentions", "dateSeance_day": "Mois"})
)

# Rajouter les stats en moyenne et médiannes

fig_time = px.bar(df.resample("ME", on="dateSeance_day").size())

fig_time.update_layout(
    title="Évolution mensuelle de l'investissement en valeur absolue de la famille du mot 'République' (B)",  # ajouter un titre
    xaxis_title="Date",
    yaxis_title="Occurrences",  # renommer les étiquettes d'axes
    template="plotly_white",  # changer le style du graphique
    showlegend=False,
)  # masquer la légende

# Afficher graphique et tableau
fig_time.show()
table

         Mois  Nombre de mentions
0  2021-02-28                 735
1  2018-07-31                 662
2  2019-02-28                 314
3  2021-06-30                 296
4  2020-11-30                 263
5  2018-04-30                 247
6  2023-05-31                 238
7  2017-07-31                 228
8  2019-06-30                 213
9  2017-11-30                 213
10 2021-03-31                 209
11 2022-11-30                 202
12 2024-05-31                 202
13 2020-10-31                 199
14 2023-12-31                 194
15 2023-07-31                 193
16 2019-11-30                 189
17 2018-11-30                 185
18 2018-06-30                 184
19 2018-03-31                 179
20 2020-02-29                 174
21 2022-01-31                 172
22 2024-03-31                 171
23 2018-12-31                 168
24 2018-10-31                 166
25 2023-06-30                 163
26 2023-11-30                 162
27 2022-02-28                 159
28 2022-10-31                 159
29 2017-12-31                 157
30 2023-10-31                 153
31 2021-11-30                 151
32 2021-05-31                 151
33 2023-03-31                 151
34 2020-12-31                 150
35 2017-10-31                 150
36 2019-01-31                 143
37 2018-05-31                 140
38 2019-05-31                 139
39 2021-10-31                 139
40 2020-06-30                 134
41 2019-10-31                 132
42 2022-07-31                 124
43 2019-03-31                 124
44 2019-04-30                 124
45 2022-12-31                 123
46 2018-02-28                 121
47 2021-12-31                 121
48 2023-02-28                 120
49 2024-01-31                 118

***Remarques*** : 
- 1 : séparatisme 1ere lecture
- 2 : démocratie + représentative
- 3 : école de la confiance
- 4 : séparatisme 2e lecture
- 5 : loi sécurité globale 
- 6 (interv regroupées) : immigration "maitrisée" et droit d'asile "effectif" // 6 (interv séparées) : **Mai 2023 ?**
- 7 : En **mai 2023** plusieurs dates (9 et 10, 2, 3, 16 et 23 aussi) avec par exemple discussion d'une commission sur les violences en manifestation,  // 7 (interv séparées) : souveraineté, nationalité, immigration et asile
- 8 (interv regroupées): Projet de loi pour la confiance dans la vie publique ou 8 (interv séparées) : immigration "maitrisée" et droit d'asile "effectif"
- 9 : Alsace
- 10 (interv regroupées): **novembre 2017** (loi finance ? situation internationale) // (interv séparées) : mort de Nahel et autres

### Par semaines

In [15]:
# aficher les 25 semaines les plus fréquentes sous forme de tableau
table = (
    df.resample("W", on="dateSeance_day")
      .size()
      .sort_values(ascending=False)
      .head(20)
      .reset_index()
      .rename(columns={0: "Nombre de mentions", "DateSeance_day": "Semaine"})
)

# Graphique par semaine
fig_time = px.bar(df.resample("W", on="dateSeance_day").size())

fig_time.update_layout(
    title="Évolution hebdomadaire de l'investissement en valeur absolue de la famille du mot 'République' (B)",  
    xaxis_title="Date",
    yaxis_title="Nombre de mentions",  
    template="plotly_white", 
    showlegend=False,
)  

# Afficher le graphique
fig_time.show()
table

   dateSeance_day  Nombre de mentions
0      2021-02-07                 403
1      2021-02-14                 279
2      2018-07-15                 274
3      2018-07-22                 227
4      2021-07-04                 212
5      2019-02-17                 202
6      2018-04-22                 177
7      2020-11-22                 147
8      2017-07-30                 125
9      2017-10-01                 110
10     2019-02-03                 101
11     2023-12-10                  98
12     2022-11-20                  98
13     2020-11-01                  93
14     2020-12-06                  90
15     2018-07-29                  87
16     2024-05-19                  83
17     2019-06-23                  81
18     2018-04-01                  80
19     2023-01-15                  79

***Remarques***
- (1-2-5/4) : principe de la république & séparatisme
- (3-4/5) : démocratie + représentative
- (6) : école de la confiance
- (7) : immigration maitrisée et droit d'asile
- (8) : prééminence des lois de la République & loi relative à la sécurité globale
- (9) : Projet de loi pour la confiance dans la vie publique
- (10) : **octobre 2017 ?**

### Par jours

In [37]:
table = df["dateSeance_day"].value_counts()[0:40].reset_index()
table = table.rename(columns={"count": "Nombre de mentions"})

# Graphique par jour (illisible)
fig_time = px.line(df.resample("D", on="dateSeance_day").size())

fig_time.update_layout(
    title="Évolution journalier de l'investissement en valeur absolue de la famille du mot 'République' (B)",  
    xaxis_title="Date",
    yaxis_title="Nombre de mentions",  # renommer les étiquettes d'axes
    template="plotly_white",  # changer le style du graphique
    showlegend=False,
)  # masquer la légende

# Afficher le graphique et le tableau
fig_time.show()
table

   dateSeance_day  Nombre de mentions
0      2021-02-05                 170
1      2018-07-12                  98
2      2021-02-12                  97
3      2021-02-11                  88
4      2021-02-04                  81
5      2021-02-03                  70
6      2023-12-07                  65
7      2018-07-11                  63
8      2021-06-30                  62
9      2021-06-28                  62
10     2020-12-03                  60
11     2020-11-20                  58
12     2019-02-11                  55
13     2019-06-24                  53
14     2018-04-22                  52
15     2021-02-01                  51
16     2019-02-12                  51
17     2018-07-19                  51
18     2018-07-26                  50
19     2018-07-13                  49
20     2022-11-18                  49
21     2019-01-29                  49
22     2018-07-10                  49
23     2018-07-16                  48
24     2021-06-29                  47
25     2024-03-06                  47
26     2017-07-28                  47
27     2019-04-03                  46
28     2023-05-10                  45
29     2023-01-12                  44
30     2023-04-05                  43
31     2023-07-04                  42
32     2023-07-11                  41
33     2021-07-01                  41
34     2022-02-09                  40
35     2017-09-26                  39
36     2019-02-15                  39
37     2018-07-17                  37
38     2021-02-13                  37
39     2024-05-13                  36

**Remarques**

- 5 des 6 jours les plus saillants sont lors des deux semaines de discussion du projet de loi "Respect des principes de la République" et 9
- 12, 10 et 11 juillet 2018 (démocratie + représentative)
- 7 décembre 2023 : discussion de la proposition de loi constitutionnelle relative à la souveraineté de la France, à la nationalité, à l’immigration et à l’asile
- 3 décembre 2020 : Prééminence des lois de la République
- 12 janvier 2023 : Surtout le Port d’une tenue uniforme à l’école mais aussi Revivifier la représentation politique
- 20 novembre 2020 : loi sécurité globale
- 4 juillet 2023 : Mort de Nahel et violences urbaines 
- 24 juin 2019 : statut de la collectivité alsacienne (territoires)
- 18 novembre 2022 : Orientation et programmation du ministère de l’intérieur
- 3 avril 2019 : Débat sur la démocratie et la citoyenneté

### Statistiques générales périodes

In [35]:
def stats_générales(df, periode="semaine"):

    # Définir la granularité
    if periode == "semaine":
        df["periode"] = (
            df["dateSeance_day"].dt.isocalendar().year.astype(str)
            + "-W"
            + df["dateSeance_day"].dt.isocalendar().week.astype(str)
        )
    elif periode == "mois":
        df["periode"] = df["dateSeance_day"].dt.to_period("M").astype(str)
    elif periode == "annee":
        df["periode"] = df["dateSeance_day"].dt.year.astype(str)
    else:
        raise ValueError("periode doit être 'semaine', 'mois' ou 'annee'")

    # Compter le nombre d'interventions par période
    df_counts = df.groupby("periode").size().reset_index(name="occurrences")

    # Calculer la moyenne et la médiane
    moyenne = df_counts["occurrences"].mean()
    mediane = df_counts["occurrences"].median()
    descriptions = df_counts["occurrences"].describe()

    return moyenne, mediane, max, descriptions, df_counts


# Statistiques par semaine
moyenne, mediane, max, descriptions, df_semaine = stats_générales(df, periode="semaine")
print(f"Moyenne/semaine: {moyenne:.2f}, Médiane/semaine: {mediane}, Données descriptives {descriptions}")

# Statistiques par mois
moyenne, mediane, max, descriptions, df_mois = stats_générales(df, periode="mois")
print(f"Moyenne/mois: {moyenne:.2f}, Médiane/mois: {mediane}, Données descriptives {descriptions}")

# Statistiques par année
moyenne, mediane,max, descriptions, df_annee = stats_générales(df,periode="annee")
print(f"Moyenne/an: {moyenne:.2f}, Médiane/an: {mediane}, Données descriptives {descriptions}")

Moyenne/semaine: 43.62, Médiane/semaine: 35.0, Données descriptives count    262.000000
mean      43.622137
std       42.701117
min        1.000000
25%       23.000000
50%       35.000000
75%       49.750000
max      403.000000
Name: occurrences, dtype: float64
Moyenne/mois: 148.43, Médiane/mois: 139.0, Données descriptives count     77.000000
mean     148.428571
std      112.334138
min        1.000000
25%       93.000000
50%      139.000000
75%      179.000000
max      735.000000
Name: occurrences, dtype: float64
Moyenne/an: 1428.62, Médiane/an: 1443.0, Données descriptives count       8.00000
mean     1428.62500
std       565.86443
min       692.00000
25%       954.25000
50%      1443.00000
75%      1752.75000
max      2215.00000
Name: occurrences, dtype: float64

### Par période sur corpus annualisés

In [21]:
# Choisir une année
annee = 2021

# Filtrer le DataFrame sur l'année choisie
df_annee = df[df["dateSeance_day"].dt.year == annee]

# aficher les 25 dates les plus fréquentes d'une année sous forme de tableau
table = (
    df_annee.resample("W", on="dateSeance_day") # remplacer D par W ou ME pour changer la période 
      .size()
      .sort_values(ascending=False)
      .head(20)
      .reset_index()
      .rename(columns={0: "Nombre de mentions", "dateSeance_day": "Semaine"})
)
table

      Semaine  Nombre de mentions
0  2021-02-07                 403
1  2021-02-14                 279
2  2021-07-04                 212
3  2021-03-14                  74
4  2021-10-31                  73
5  2021-05-09                  54
6  2021-02-21                  53
7  2021-07-25                  52
8  2021-12-12                  51
9  2021-04-11                  49
10 2021-12-05                  48
11 2021-03-28                  47
12 2021-06-20                  43
13 2021-11-21                  41
14 2021-05-30                  39
15 2021-03-21                  38
16 2021-05-23                  38
17 2021-04-04                  35
18 2021-11-07                  35
19 2021-03-07                  35

In [23]:
# Graphique par jour sur une année 

# Choisir une année
annee = 2021

# Filtrer le DataFrame sur l'année choisie
df_annee = df[df["dateSeance_day"].dt.year == annee]

# Resampler par jour uniquement pour cette année
df_daily = df_annee.resample("W", on="dateSeance_day").size().reset_index() # remplacer D par W ou ME pour changer la période

# Tracer le graphique
fig_daily = px.bar(
    df_daily,
    x="dateSeance_day",
    y=0,
    title=f"Évolution (X) de l'investissement en valeur absolue de la famille du mot 'République' (B) en {annee}",
    labels={"dateSeance_day": "Date", "0": "Occurrences"},
    template="plotly_white",
)

fig_daily.update_layout(showlegend=False)

fig_daily.show()

## Par groupes

### Sur total

In [ ]:
fig_partis_1 = px.bar(
    df["groupe_députés_affiliation"].value_counts()[0:15],
    # x=top_counts.index,
    # y=top_counts.values,
    labels={"value": "Nombre d'occurence", "groupe_députés_affiliation": "Groupes parlementaires"},
    title="Occurrences de la 'République' en valeur absolue par groupes parlementaires",
    template="plotly_white",
)
fig_partis_1.update_layout(
    xaxis_tickangle=-45,
    showlegend=False,
)
fig_partis_1.show()

# Variable d’affiliation politique des simples députés hors gouvernement
df["groupe_députés_affiliation"].value_counts()

In [ ]:
fig_partis_2 = px.bar(
    df["groupe_all_affiliation"].value_counts()[0:15],
    # x=top_counts.index,
    # y=top_counts.values,
    labels={"value": "Nombre d'occurence", "groupe_all_affiliation": "Affiliations (gouvernement inclus)"},
    title="Occurrences de la 'République' en valeur absolue par affiliation politique",
    template="plotly_white",
)
fig_partis_2.update_layout(
    xaxis_tickangle=-45,
    showlegend=False,
)
fig_partis_2.show()

# Variable d’affiliation politique par groupe parlementaire hors considération des positions
df["groupe_all_affiliation"].value_counts()

In [ ]:
fig_partis_3 = px.bar(
    df["groupe&gvt_affiliation"].value_counts()[0:15],
    # x=top_counts.index,
    # y=top_counts.values,
    labels={"value": "Nombre d'occurence", "groupe&gvt_affiliation": "Groupes parlementaires + Gouvernement"},
    title="Occurrences de la 'République' en valeur absolue par groupes parlementaires (+ Gouvernement)",
    template="plotly_white",
)
fig_partis_3.update_layout(
    xaxis_tickangle=-45,
    showlegend=False,
)
fig_partis_3.show()

# Variable d’affiliation politique par groupe parlementaire + gouvernement séparé
df["groupe&gvt_affiliation"].value_counts()

### Évolution sur le total

In [ ]:
# TODO : changer manuellement les couleurs des graphiques

def groupes_evolutions(df, date_col="dateSeance_day", parti_col="groupe&gvt_affiliation", top_n=7):

    # Filtrer le top des partis
    top_partis = df[parti_col].value_counts().nlargest(top_n).index.tolist()

    # Filtrer les données pour ces partis uniquement
    df_top = df[df[parti_col].isin(top_partis)]

    # Grouper par année et parti
    df_grouped = (
        df_top.groupby([pd.Grouper(key=date_col, freq="Y"), parti_col])
        .size()
        .reset_index(name="mentions")
    )

    # Extraire l'année pour affichage clair
    df_grouped["Année"] = df_grouped[date_col].dt.year

    # Tracer avec plotly express
    fig = px.line(
        df_grouped,
        x="Année",
        y="mentions",
        color=parti_col,
        markers=True,
        title=f"Évolution annuelle des occurrences de la République du top {top_n} des groupes parlementaires + gvt",
        labels={"mentions": "Occurrences", parti_col: "Affiliations politiques (gouvernement inclu)"}
    )

    fig.update_layout(
        xaxis=dict(dtick=1),
        hovermode="x unified",
        template="plotly_white",
        legend_title_text="Groupe parlementaire + GVT"
    )

    fig.show()

In [ ]:
groupes_evolutions(df)

### Par périodes

In [ ]:
def partis_periodique(df, parti_col="groupe_députés_affiliation", periode="annee", annee=2021, semaine=None, jour=None, 
                 date_debut=None, date_fin=None, jours=None, top_n=None):

    # --- Filtrage selon la période ---
    if periode == "annee":
        df_filtered = df[df["dateSeance_day"].dt.year == annee]
        titre = f"Groupes mobilisant le plus la 'République' en {annee} à l'Assemblée Nationale (valeur absolue)"

    elif periode == "semaine":
        if annee is None or semaine is None:
            raise ValueError("Il faut préciser l'année et la semaine pour periode='semaine'")
        df_filtered = df[
            (df["dateSeance_day"].dt.isocalendar().year == annee) &
            (df["dateSeance_day"].dt.isocalendar().week == semaine)
        ]
        titre = f"Groupes mobilisant le plus la 'République' la {semaine}e semaine {annee} à l'Assemblée Nationale (valeur absolue)"

    elif periode == "jour":
        if jour is None:
            raise ValueError("Il faut préciser la date pour periode='jour'")
        jour_dt = pd.to_datetime(jour).date()
        df_filtered = df[df["dateSeance_day"].dt.date == jour_dt]
        titre = f"Groupes mobilisant le plus la 'République' le {jour_dt} (en valeur absolue)"

    elif periode == "intervalle":
        if date_debut is None or date_fin is None:
            raise ValueError("Il faut préciser date_debut et date_fin pour periode='intervalle'")
        debut = pd.to_datetime(date_debut)
        fin = pd.to_datetime(date_fin)
        df_filtered = df[(df["dateSeance_day"] >= debut) & (df["dateSeance_day"] <= fin)]
        titre = f"Groupes mobilisant le plus la 'République' du {debut.date()} au {fin.date()}"

    elif periode == "jours":
        if jours is None or not isinstance(jours, (list, tuple)):
            raise ValueError("Il faut fournir une liste de dates pour periode='jours'")
        jours_dt = [pd.to_datetime(j).date() for j in jours]
        df_filtered = df[df["dateSeance_day"].dt.date.isin(jours_dt)]
        titre = f"Partis mobilisant le plus la 'République' lors de X évènement"

    else:
        raise ValueError("periode doit être 'annee', 'semaine', 'jour', 'intervalle' ou 'jours'")

    # --- Comptage des orateurs ---
    df_counts = df_filtered[parti_col].value_counts().head(top_n).reset_index()
    df_counts.columns = [parti_col, "occurrences"]

    # --- Graphique ---
    fig = px.bar(
        df_counts,
        x=parti_col,
        y="occurrences",
        title=titre,
        template="plotly_white",
    )
    fig.update_layout(xaxis_tickangle=-45, showlegend=False)
    fig.show()
    return df_counts

In [ ]:
# Partis par année
partis_periodique(df, periode="annee", annee=2017, top_n=12)

In [ ]:
# Partis sur la semaine X de X
partis_periodique(df, periode="semaine", annee=2021, semaine=6)

In [ ]:
# Partis (tel jour) le X 
partis_periodique(df, periode="jour", jour="2021-02-01")

In [ ]:
# Partis (sur telle période) du 1er au 16 février 2021
partis_periodique(df, periode="intervalle", date_debut="2021-02-01", date_fin="2021-02-16")

#### Évolutions sur périodes

In [ ]:
# TODO : changer manuellement les couleurs des graphiques

def groupes_evolutions_périodique(df, date_col="dateSeance_day", parti_col="groupe_députés_affiliation", top_n=7, start_year=2021, end_year=2021):

    # Filtrer par période si spécifiée
    if start_year or end_year:
        mask = pd.Series(True, index=df.index)
        if start_year:
            mask &= df[date_col].dt.year >= start_year
        if end_year:
            mask &= df[date_col].dt.year <= end_year
        df = df.loc[mask].copy()
    
    # Filtrer le top des partis
    top_partis = df[parti_col].value_counts().nlargest(top_n).index.tolist()

    # Filtrer les données pour ces partis uniquement
    df_top = df[df[parti_col].isin(top_partis)]

    # Grouper par année et parti
    df_grouped = (
        df_top.groupby([pd.Grouper(key=date_col, freq="M"), parti_col])
        .size()
        .reset_index(name="mentions")
    )

    # Extraire l'année pour affichage clair
    df_grouped["Année"] = df_grouped[date_col].dt.year
    df_grouped["Mois"] = df_grouped[date_col].dt.strftime("%Y-%m")

    # Tracer avec plotly express
    fig = px.line(
        df_grouped,
        x="Mois",
        y="mentions",
        color=parti_col,
        markers=True,
        title=(
            f"Évolution annuelle du % d'utilisation du mot 'République' "
            f"({top_n} principaux groupes, {start_year or df_grouped['Année'].min()}–{end_year or df_grouped['Année'].max()})"
        ),
        labels={"mentions": "Occurences", parti_col: "Groupe parlementaire"}
    )

    fig.update_layout(
        xaxis=dict(dtick="M1", tickangle=45),
        hovermode="x unified",
        template="plotly_white",
        legend_title_text="Groupe",
        yaxis_tickformat="Mentions"
    )

    fig.show()
    return df_top

In [ ]:
groupes_evolutions_périodique(df)

## Par personnel politique / individuellement

#### Les principaux orateurs sur la période / par législature

In [ ]:
fig_top_orateurs = px.bar(
    df["nom_orateur_clean"].value_counts()[0:10],
    # x=top_counts.index,
    # y=top_counts.values,
    labels={"value": "Nombre d'occurence", "nom_orateur_clean": "Personnel politique"},
    title="Top 20 personnel politique par occurence de la République",
    template="plotly_white",
)
fig_top_orateurs.update_layout(
    xaxis_tickangle=-45,
    showlegend=False,
)
fig_top_orateurs.show()
df["nom_orateur_clean"].value_counts()[0:20]

#### Évolutions sur la période

In [ ]:
# TODO : changer manuellement les couleurs des graphiques

def personnel_evolutions(df, date_col="dateSeance_day", personnel_col="nom_orateur_clean", top_n=7):

    # Filtrer le top des partis
    top_personnel = df[personnel_col].value_counts().nlargest(top_n).index.tolist()

    # Filtrer les données pour ces partis uniquement
    df_top = df[df[personnel_col].isin(top_personnel)]

    # Grouper par année et parti
    df_grouped = (
        df_top.groupby([pd.Grouper(key=date_col, freq="Y"), personnel_col])
        .size()
        .reset_index(name="mentions")
    )

    # Extraire l'année pour affichage clair
    df_grouped["Année"] = df_grouped[date_col].dt.year

    # Tracer avec plotly express
    fig = px.line(
        df_grouped,
        x="Année",
        y="mentions",
        color=personnel_col,
        markers=True,
        title=f"Évolution annuelle des occurrences de la République des {top_n} principaux personnels politiques",
        labels={"mentions": "Occurrences", personnel_col: "Affiliations politiques (gouvernement inclu)"}
    )

    fig.update_layout(
        xaxis=dict(dtick=1),
        hovermode="x unified",
        template="plotly_white",
        legend_title_text="Personnel politique"
    )

    fig.show()

In [ ]:
personnel_evolutions(df)

##### Évolutions sur courtes périodes

In [ ]:
# TODO : changer manuellement les couleurs des graphiques

def personnel_evolutions_périodique(df, date_col="dateSeance_day", personnel_col="nom_orateur_clean", top_n=7, start_year=2018, end_year=2020):

    # Filtrer par période si spécifiée
    if start_year or end_year:
        mask = pd.Series(True, index=df.index)
        if start_year:
            mask &= df[date_col].dt.year >= start_year
        if end_year:
            mask &= df[date_col].dt.year <= end_year
        df = df.loc[mask].copy()
    
    # Filtrer le top des partis
    top_personnel = df[personnel_col].value_counts().nlargest(top_n).index.tolist()

    # Filtrer les données pour ces partis uniquement
    df_top = df[df[personnel_col].isin(top_personnel)]

    # Grouper par année et parti
    df_grouped = (
        df_top.groupby([pd.Grouper(key=date_col, freq="M"), personnel_col])
        .size()
        .reset_index(name="mentions")
    )

    # Extraire l'année pour affichage clair
    df_grouped["Année"] = df_grouped[date_col].dt.year
    df_grouped["Mois"] = df_grouped[date_col].dt.strftime("%Y-%m")

    # Tracer avec plotly express
    fig = px.line(
        df_grouped,
        x="Mois",
        y="mentions",
        color=personnel_col,
        markers=True,
        title=(
            f"Évolution annuelle des occurences d'utilisation du mot 'République' "
            f"({top_n} principaux groupes, {start_year or df_grouped['Année'].min()}–{end_year or df_grouped['Année'].max()})"
        ),
        labels={"mentions": "Occurences", personnel_col: "Groupe parlementaire"}
    )

    fig.update_layout(
        xaxis=dict(dtick="M1", tickangle=45),
        hovermode="x unified",
        template="plotly_white",
        legend_title_text="Groupe",
        yaxis_tickformat="Mentions"
    )

    fig.show()

In [ ]:
personnel_evolutions_périodique(df)

##### Statistiques sur les évolutions

In [27]:
from plotly.subplots import make_subplots
import plotly.graph_objects as go

# Top 10 orateurs
top_orateurs = df["nom_orateur"].value_counts().index[:10].tolist()

# Grouper par semaine et orateur
df_orateur = df[df["nom_orateur"].isin(top_orateurs)]
df_grouped_orateur = (
    df_orateur.groupby([pd.Grouper(key="dateSeance_day", freq="MS"), "nom_orateur"])
    .size()
    .reset_index(name="mentions")
)

cols = 4
rows = (len(top_orateurs) + cols - 1) // cols
max_y = df_grouped_orateur["mentions"].max()

fig_orateurs_time = make_subplots(
    rows=rows, cols=cols, shared_xaxes=True, subplot_titles=top_orateurs
)

for idx, orateur in enumerate(top_orateurs):
    row = idx // cols + 1
    col = idx % cols + 1
    data_orateur = df_grouped_orateur[df_grouped_orateur["nom_orateur"] == orateur]
    fig_orateurs_time.add_trace(
        go.Bar(
            x=data_orateur["dateSeance_day"], y=data_orateur["mentions"], name=orateur
        ),
        row=row,
        col=col,
    )

fig_orateurs_time.update_layout(
    height=300 * rows,
    width=1200,
    title_text="Dynamique temporelle des mentions par orateur",
    showlegend=False,
    template="plotly_white",
)

for row in range(1, rows + 1):
    for col in range(1, cols + 1):
        fig_orateurs_time.update_yaxes(range=[0, max_y], row=row, col=col)

for col in range(1, cols + 1):
    fig_orateurs_time.update_xaxes(title_text="Date", row=rows, col=col)

for row in range(1, rows + 1):
    fig_orateurs_time.update_yaxes(title_text="Nombre de mentions", row=row, col=1)

fig_orateurs_time.show()

#### Principaux orateurs par législatures

In [ ]:
df_16e = df [df["legislature"]== 16]
df_15e = df [df["legislature"]== 15]

In [ ]:
# 15e législature 
fig_top_orateurs = px.bar(
    df_15e["nom_orateur_clean"].value_counts()[0:10],
    # x=top_counts.index,
    # y=top_counts.values,
    labels={"value": "Nombre d'occurence", "Personnel politique": "Orateur"},
    title="Top 20 personnel politique par occurence de la République lors de la 15e législature",
    template="plotly_white",
)
fig_top_orateurs.update_layout(
    xaxis_tickangle=-45,
    showlegend=False,
)
fig_top_orateurs.show()
df_15e["nom_orateur_clean"].value_counts()[0:20]

In [ ]:
# 16e législature 
fig_top_orateurs = px.bar(
    df_16e["nom_orateur_clean"].value_counts()[0:10],
    # x=top_counts.index,
    # y=top_counts.values,
    labels={"value": "Nombre d'occurence", "Personnel politique": "Orateur"},
    title="Top 20 personnel politique par occurence de la République lors de la 16e législature",
    template="plotly_white",
)
fig_top_orateurs.update_layout(
    xaxis_tickangle=-45,
    showlegend=False,
)
fig_top_orateurs.show()
df_16e["nom_orateur_clean"].value_counts()[0:20]

In [ ]:
# Pour la 15e législature 

from plotly.subplots import make_subplots
import plotly.graph_objects as go

# Top 10 orateurs
top_orateurs = df_15e[""nom_orateur_clean" : "Personnel politique""].value_counts().index[:4].tolist()

# Grouper par semaine et orateur
df_orateur_15e = df_15e[df_15e["nom_orateur"].isin(top_orateurs)]
df_grouped_orateur_15e = (
    df_orateur_15e.groupby([pd.Grouper(key="dateSeance_day", freq="MS"), "nom_orateur"])
    .size()
    .reset_index(name="mentions")
)

cols = 4
rows = (len(top_orateurs) + cols - 1) // cols
max_y = df_grouped_orateur_15e["mentions"].max()

fig_orateurs_time = make_subplots(
    rows=rows, cols=cols, shared_xaxes=True, subplot_titles=top_orateurs
)

for idx, orateur in enumerate(top_orateurs):
    row = idx // cols + 1
    col = idx % cols + 1
    data_orateur = df_grouped_orateur_15e[df_grouped_orateur_15e["nom_orateur"] == orateur]
    fig_orateurs_time.add_trace(
        go.Bar(
            x=data_orateur["dateSeance_day"], y=data_orateur["mentions"], name=orateur
        ),
        row=row,
        col=col,
    )

fig_orateurs_time.update_layout(
    height=300 * rows,
    width=1200,
    title_text="Dynamique temporelle des mentions par orateur",
    showlegend=False,
    template="plotly_white",
)

for row in range(1, rows + 1):
    for col in range(1, cols + 1):
        fig_orateurs_time.update_yaxes(range=[0, max_y], row=row, col=col)

for col in range(1, cols + 1):
    fig_orateurs_time.update_xaxes(title_text="Date", row=rows, col=col)

for row in range(1, rows + 1):
    fig_orateurs_time.update_yaxes(title_text="Nombre de mentions", row=row, col=1)

fig_orateurs_time.show()

#### Les principaux orateurs par années/semaines/séances

In [ ]:
def top_orateurs_periodique(df, periode="annee", annee=2021, semaine=None, jour=None, 
                 date_debut=None, date_fin=None, jours=None, top_n=10):

    # --- Filtrage selon la période ---
    if periode == "annee":
        df_filtered = df[df["dateSeance_day"].dt.year == annee]
        titre = f"Top {top_n} du personnel politique mobilisant le plus la 'République' en {annee} à l'Assemblée Nationale (valeur absolue)"

    elif periode == "semaine":
        if annee is None or semaine is None:
            raise ValueError("Il faut préciser l'année et la semaine pour periode='semaine'")
        df_filtered = df[
            (df["dateSeance_day"].dt.isocalendar().year == annee) &
            (df["dateSeance_day"].dt.isocalendar().week == semaine)
        ]
        titre = f"Top {top_n} du personnel politique mobilisant le plus la 'République' la {semaine}e semaine {annee} à l'Assemblée Nationale (valeur absolue)"

    elif periode == "jour":
        if jour is None:
            raise ValueError("Il faut préciser la date pour periode='jour'")
        jour_dt = pd.to_datetime(jour).date()
        df_filtered = df[df["dateSeance_day"].dt.date == jour_dt]
        titre = f"Top {top_n} du personnel politique mobilisant le plus la 'République' le {jour_dt} (en valeur absolue)"

    elif periode == "intervalle":
        if date_debut is None or date_fin is None:
            raise ValueError("Il faut préciser date_debut et date_fin pour periode='intervalle'")
        debut = pd.to_datetime(date_debut)
        fin = pd.to_datetime(date_fin)
        df_filtered = df[(df["dateSeance_day"] >= debut) & (df["dateSeance_day"] <= fin)]
        titre = f"Top {top_n} du personnel politique mobilisant le plus la 'République' du {debut.date()} au {fin.date()}"

    elif periode == "jours":
        if jours is None or not isinstance(jours, (list, tuple)):
            raise ValueError("Il faut fournir une liste de dates pour periode='jours'")
        jours_dt = [pd.to_datetime(j).date() for j in jours]
        df_filtered = df[df["dateSeance_day"].dt.date.isin(jours_dt)]
        titre = f"Top {top_n} du personnel politique mobilisant le plus la 'République' lors de X évènement"

    else:
        raise ValueError("periode doit être 'annee', 'semaine', 'jour', 'intervalle' ou 'jours'")

    # --- Comptage des orateurs ---
    df_counts = df_filtered["nom_orateur_clean"].value_counts().head(top_n).reset_index()
    df_counts.columns = ["nom_orateur_clean", "occurrences"]

    # --- Graphique ---
    fig = px.bar(
        df_counts,
        x="nom_orateur_clean",
        y="occurrences",
        title=titre,
        template="plotly_white",
    )
    fig.update_layout(xaxis_tickangle=-45, showlegend=False, yaxis_title="Occurrences totales", xaxis_title="Personnel politique")
    fig.show()
    return df_counts

In [ ]:
# Top 10 orateurs sur l'année X
top_orateurs_periodique(df, periode="annee", annee=2024)

In [ ]:
# Top 10 orateurs sur la semaine X de X
top_orateurs_periodique(df, periode="semaine", annee=2021, semaine=6)

In [ ]:
# Top 10 orateurs (tel jour) le X 
top_orateurs_periodique(df, periode="jour", jour="2021-02-01")

In [ ]:
# Top 10 orateurs (sur telle période) du 1er au 16 février 2021
top_orateurs_periodique(df, periode="intervalle", date_debut="2021-02-01", date_fin="2021-02-16")

In [ ]:
# Top 10 orateurs sur des jours spécifiques
top_orateurs_periodique(df, periode="jours", jours=["2021-02-01", "2021-02-02", "2021-02-03", "2021-02-4", "2021-02-05"])

#### Analyse discussion du projet de loi séparatisme

In [ ]:
# Top 10 orateurs lors de la 1ère discussion du projet de loi séparatisme 
top_orateurs_periodique(df, periode="jours", jours=["2021-02-01", "2021-02-02", "2021-02-03", "2021-02-04", "2021-02-05", "2021-02-08", "2021-02-10", "2021-02-11", "2021-02-12", "2021-02-13", "2021-02-16"])

In [ ]:
# Top 10 orateurs lors des discussions du projet de loi séparatisme 
top_orateurs_periodique(df, periode="jours", jours=["2021-02-01", "2021-02-02", "2021-02-03", "2021-02-04", "2021-02-05", "2021-02-08", "2021-02-10", "2021-02-11", "2021-02-12", "2021-02-13", "2021-02-16", "2021-06-28", "2021-06-29", "2021-06-30", "2021-07-01", "2021-01-23"])

In [ ]:
# Top 10 orateurs lors de la deuxième phase de discussion post débat Sénat 
top_orateurs_periodique(df, periode="jours", jours=["2021-06-28", "2021-06-29", "2021-06-30", "2021-07-01", "2021-01-23"])

### Évolution dans le temps de la fréquence d'utilisation de personnes spécifiques

In [ ]:
def stats_orateur(df, orateur, periode="semaine"):

   
    # Filtrer sur l'orateur choisi
    df_orateur = df[df["nom_orateur_clean"] == orateur].copy()
    if df_orateur.empty:
        raise ValueError(f"Aucune donnée trouvée pour l'orateur : {orateur}")

    # Définir la granularité
    if periode == "semaine":
        df_orateur["periode"] = (
            df_orateur["dateSeance_day"].dt.isocalendar().year.astype(str)
            + "-W"
            + df_orateur["dateSeance_day"].dt.isocalendar().week.astype(str)
        )
    elif periode == "mois":
        df_orateur["periode"] = df_orateur["dateSeance_day"].dt.to_period("M").astype(str)
    elif periode == "annee":
        df_orateur["periode"] = df_orateur["dateSeance_day"].dt.year.astype(str)
    else:
        raise ValueError("periode doit être 'semaine', 'mois' ou 'annee'")

    # Compter le nombre d'interventions par période
    df_counts = df_orateur.groupby("periode").size().reset_index(name="occurrences")

    # Calculer la moyenne et la médiane
    moyenne = df_counts["occurrences"].mean()
    mediane = df_counts["occurrences"].median()

    return moyenne, mediane, df_counts

In [ ]:
# Définir la personne recherchée 
orateur = "M. Gérald Darmanin"

# Statistiques par semaine
moyenne, mediane, df_semaine = stats_orateur(df, orateur, periode="semaine")
print(f"{orateur} - Moyenne/semaine: {moyenne:.2f}, Médiane/semaine: {mediane}")

# Statistiques par mois
moyenne, mediane, df_mois = stats_orateur(df, orateur, periode="mois")
print(f"{orateur} - Moyenne/mois: {moyenne:.2f}, Médiane/mois: {mediane}")

# Statistiques par année
moyenne, mediane, df_annee = stats_orateur(df, orateur, periode="annee")
print(f"{orateur} - Moyenne/an: {moyenne:.2f}, Médiane/an: {mediane}")

In [ ]:
# Graphique de l'évolution de personnes cibles par mois

# Définir la personne recherchée 
orateur = "M. Gérald Darmanin"

# Filtrer le DataFrame sur l'année choisie
df_orateur = df[df["nom_orateur_clean"]== orateur]

# Resampler par semaine uniquement pour cette année
df_monthly = df_orateur.resample("M", on="dateSeance_day").size().reset_index()

# Tracer le graphique
fig_time = px.bar(
    df_monthly,
    x="dateSeance_day",
    y=0,
    title=f"Évolution des occurrences mensuelles de la 'République' par {orateur}",
    labels={"dateSeance_day": "Date", 0: "Occurrences"},
    template="plotly_white",
)

fig_time.update_layout(showlegend=False)

fig_time.show()

## Personnel politique par groupes

In [ ]:
# Fonction générale 

# Définir la personne recherchée 
parti = "ECO"

# Filtrer sur le parti choisi
df_partis = df[df["groupe_députés_affiliation"] == parti]

# Figure
fig_top_orateurs_partis = px.bar(
    df_partis["nom_orateur_clean"].value_counts()[0:10],
    # x=top_counts.index,
    # y=top_counts.values,
    labels={"value": "Nombre d'occurence", "nom_orateur_clean": "Député.es"},
    title= f"Top 10 des député.es {parti} en nb d'occurrences de la 'République'",
    template="plotly_white",
)
fig_top_orateurs_partis.update_layout(
    xaxis_tickangle=-45,
    showlegend=False,
)
fig_top_orateurs_partis.show()

# Tableaux 
df_partis["nom_orateur_clean"].value_counts()[0:10]

### Genre (nécessite d'avoir fait la fusion)

In [ ]:
df["civ"] = df["civ"].replace({"M.": "Homme", "Mme": "Femme"})

In [ ]:
fig = px.bar(df["civ"].value_counts())
fig.update_layout(
    title="Répartition des genres (civ)", template="plotly_white", showlegend=False
)
fig.show()

## Autres variables (à compléter et faire plus sérieusement)

### Mandat

### Proximité avec la majorité 

scoreMajorite

In [ ]:
df["scoreMajorite"].value_counts()

### Expérience

In [ ]:
df["experienceDepute"].value_counts()

In [ ]:
df["age"].value_counts()

### Aire géographique 

departementCode

In [ ]:
df["departementCode"].value_counts()

## Tests régressions linéaires

In [ ]:
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

def regression_lineaire(y_col, x_cols):
    """
    Effectue une régression linéaire simple ou multiple à partir d'un CSV.
    
    csv_path : chemin du fichier CSV
    y_col : nom de la colonne cible (str)
    x_cols : liste des colonnes explicatives (list de str)
    """
   
    
    # Définir X et y
    X = df[x_cols].values
    y = df[y_col].values
    
    # Créer et entraîner le modèle
    model = LinearRegression()
    model.fit(X, y)
    
    # Prédictions
    y_pred = model.predict(X)
    
    # Résultats
    print("✅ Régression terminée")
    print("Coefficient(s):", model.coef_)
    print("Intercept:", model.intercept_)
    print("Score R²:", model.score(X, y))
    
    # Si une seule variable explicative, on affiche un graphique
    if len(x_cols) == 1:
        plt.scatter(X, y, color="blue", label="Données réelles")
        plt.plot(X, y_pred, color="red", label="Régression")
        plt.xlabel(x_cols[0])
        plt.ylabel(y_col)
        plt.legend()
        plt.show()
    
    return model

In [ ]:
modele = regression_lineaire("../data/interim/df_repu.csv", y_col=["Texte"], x_cols=["parti_affiliation", "Nom_orateur", "age"])