# 4 - Analyses statistiques (proportion)

L'objectif ici est de reproduire toutes les analyses statistiques de base sur la république en utilisant les occurrences en proportion de la parole totale ou ici plus exactement la proportion d'énoncés mobilisant l'idée de république sur tous les énoncés. 
Pour cela on prend le fichier de base auquel on a ajouté la colonne avec le résultat de la regex en true/false.

In [1]:
import pandas as pd
import plotly.express as px

In [2]:
df = pd.read_csv(
    "../data/interim/df_identification_republi_simple.csv", low_memory=False, dtype={"ID_orateur": str}
)

In [3]:
import datetime
import locale

# Active la locale française (nécessaire pour le format)
locale.setlocale(locale.LC_TIME, "fr_FR.UTF-8")

'fr_FR.UTF-8'

In [4]:
df["dateSeance_ts"] = pd.to_datetime(df["dateSeanceJour"], format="%A %d %B %Y")
df["dateSeance_day"] = df["dateSeance_ts"].dt.normalize()

## Analyses générales temporelles

### Par jours

#### Par jours sur corpus intégral

In [5]:
# Compter True/False par jour
df_daily = (
    df.groupby(df["dateSeance_day"].dt.date)["repu_match_valide"]
    .value_counts(normalize=True)  # calcule directement les proportions
    .rename("proportion")
    .reset_index()
)

# Garder uniquement les "True"
df_daily_true = df_daily[df_daily["repu_match_valide"] == True]

# aficher les 25 dates les plus fréquentes sous forme de tableau
table = df_daily_true.sort_values("proportion", ascending=False).head(20)
table

     dateSeance_day  repu_match_valide  proportion
4        2017-07-03               True    0.380952
1084     2021-02-01               True    0.335404
1908     2024-03-04               True    0.255319
316      2018-07-09               True    0.254902
1236     2021-06-28               True    0.248503
839      2020-03-22               True    0.235294
1092     2021-02-05               True    0.224684
1262     2021-07-23               True    0.167598
1088     2021-02-03               True    0.137255
500      2019-02-11               True    0.135371
1240     2021-06-30               True    0.133333
1377     2022-01-06               True    0.132948
1654     2023-04-05               True    0.130372
1242     2021-07-01               True    0.126521
1102     2021-02-12               True    0.123862
782      2020-01-16               True    0.120690
322      2018-07-12               True    0.117428
196      2018-03-13               True    0.116883
1022     2020-11-16               True    0.113402
1100     2021-02-11               True    0.112861

**Remarques**
*Le 3 juillet 2017, le 9 juillet 2018, le 4 mars 2024 sont parmis les 5 principales dates car parlement réuni en Congrès*

*le 1 février 2021, le 28 juin 2021, 5 février 2021, le 23 juillet 2021, le 3 février 2021, 30 juin 2021 (et 5 avril 2023 : bilan de la loi), 1er juillet 2021, le 12 février 2021, renvoient quant à eux à la discussion du projet de loi "confortant le respect des principes de la République". **==> Suivre en détail le processus législatif de ce projet de loi car moment central !!***
*On a aussi le 22 mars 2020, très courte séance (commencée à 18h30) sur l’urgence du covid et un hommage*

*6 janvier 2022, 6 juin 2022, 13 mars 2018 : réforme territoriale Nouvelle-Calédonie*

*25 janvier 2024, 8 juillet 2019 et 16 janvier 2020 : accords internationaux avec présence d'expressions comme "gouvernement de la République française", de pays sous forme adjectivable (ex : "république arménienne") ou avec république en miniscule --> moins présent maintenant que exclus*

*11 février 2019 sur "l'école de la confiance"*
*12 et 13 juillet 2018 sur le  projet de loi constitutionnelle pour une Démocratie plus représentative, responsable et efficace*

In [6]:
# Compter True/False par jour
df_daily = (
    df.groupby(df["dateSeance_day"].dt.date)["repu_match_valide"]
    .value_counts(normalize=True)  # calcule directement les proportions
    .rename("proportion")
    .reset_index()
)

# Garder uniquement les "True"
df_daily_true = df_daily[df_daily["repu_match_valide"] == True]

# Graphique
fig_daily = px.line(
    df_daily_true,
    x="dateSeance_day",
    y="proportion",
    title="Proportion occurrences de la 'République' par jour",
    labels={"proportion": "% des occurences", "dateSeance_day": "Date"},
    template="plotly_white",
)

fig_daily.show()

#### Par jour sur corpus annualisé

In [7]:
# Choisir une année
annee = 2022

# Filtrer le DataFrame sur l'année choisie
df_annee = df[df["dateSeance_day"].dt.year == annee]

# Compter True/False par jour
df_daily = (
    df_annee.groupby(df["dateSeance_day"].dt.date)["repu_match_valide"]
    .value_counts(normalize=True)  # calcule directement les proportions
    .rename("proportion")
    .reset_index()
)

# Garder uniquement les "True"
df_daily_true = df_daily[df_daily["repu_match_valide"] == True]

# aficher les 25 dates les plus fréquentes sous forme de tableau
table = df_daily_true.sort_values("proportion", ascending=False).head(50)
table

    dateSeance_day  repu_match_valide  proportion
7       2022-01-06               True    0.132948
47      2022-02-09               True    0.088496
68      2022-07-06               True    0.087273
41      2022-02-03               True    0.081967
35      2022-01-31               True    0.078313
53      2022-02-16               True    0.071429
29      2022-01-25               True    0.054487
64      2022-03-01               True    0.053763
92      2022-07-27               True    0.053292
55      2022-02-17               True    0.052632
62      2022-02-24               True    0.048860
160     2022-11-22               True    0.045635
9       2022-01-07               True    0.044118
43      2022-02-04               True    0.043573
70      2022-07-11               True    0.043042
16      2022-01-13               True    0.039867
128     2022-10-24               True    0.039752
156     2022-11-18               True    0.039558
140     2022-11-03               True    0.039007
148     2022-11-14               True    0.038772
142     2022-11-04               True    0.036932
187     2022-12-11               True    0.036111
20      2022-01-16               True    0.035533
179     2022-12-06               True    0.034873
37      2022-02-01               True    0.034700
98      2022-08-03               True    0.028986
165     2022-11-25               True    0.027638
171     2022-11-30               True    0.026446
3       2022-01-04               True    0.024904
197     2022-12-17               True    0.023529
72      2022-07-12               True    0.022678
191     2022-12-13               True    0.022312
104     2022-10-04               True    0.022195
173     2022-12-01               True    0.022018
167     2022-11-28               True    0.021802
27      2022-01-20               True    0.020408
175     2022-12-02               True    0.020385
45      2022-02-08               True    0.020225
112     2022-10-11               True    0.019771
58      2022-02-22               True    0.018443
24      2022-01-18               True    0.018307
100     2022-08-04               True    0.017857
13      2022-01-11               True    0.017677
51      2022-02-15               True    0.017621
94      2022-07-28               True    0.017544
1       2022-01-03               True    0.017467
96      2022-08-02               True    0.017070
130     2022-10-25               True    0.015823
102     2022-10-03               True    0.015487
5       2022-01-05               True    0.015138

In [8]:
# Graphique
fig_daily = px.line(
    df_daily_true,
    x="dateSeance_day",
    y="proportion",
    title="Proportion occurrences de la 'République' par jour",
    labels={"proportion": "% des occurences", "dateSeance_day": "Date"},
    template="plotly_white",
)

fig_daily.show()

### Par semaine

#### Par semaine sur corpus intégral

In [9]:
# Grouper par semaine
df_weekly = (
    df.groupby(df["dateSeance_day"].dt.to_period("W"))["repu_match_valide"]
    .value_counts(normalize=True)
    .rename("proportion")
    .reset_index()
)

# Transformer la période en datetime (pour l'axe X)
df_weekly["dateSeance_day"] = df_weekly["dateSeance_day"].dt.to_timestamp()

# Garder True uniquement
df_weekly_true = df_weekly[df_weekly["repu_match_valide"] == True]

# aficher les 25 dates les plus fréquentes sous forme de tableau
table = df_weekly_true.sort_values("proportion", ascending=False).head(20)
table

    dateSeance_day  repu_match_valide  proportion
293     2021-02-01               True    0.164128
329     2021-06-28               True    0.133037
85      2018-07-09               True    0.107520
67      2018-05-07               True    0.093525
385     2022-07-04               True    0.087273
295     2021-02-08               True    0.081830
59      2018-03-26               True    0.076539
3       2017-07-03               True    0.070151
205     2020-01-13               True    0.068182
131     2019-02-11               True    0.061588
253     2020-07-13               True    0.057203
55      2018-03-12               True    0.056604
129     2019-02-04               True    0.055556
381     2022-02-28               True    0.053763
127     2019-01-28               True    0.050314
91      2018-07-30               True    0.047553
373     2022-01-31               True    0.047424
489     2023-12-11               True    0.046851
161     2019-06-17               True    0.046405
491     2023-12-18               True    0.046099

**Remarques**
- 2 premières semaines (+ S6) correspondent aux débats sur la loi « confortant le respect des principes de la République et la lutte contre le séparatisme » 
- 3e semaine correspond au débat sur la démocratie représentative

In [10]:
# Grouper par semaine
df_weekly = (
    df.groupby(df["dateSeance_day"].dt.to_period("W"))["repu_match_valide"]
    .value_counts(normalize=True)
    .rename("proportion")
    .reset_index()
)

# Transformer la période en datetime (pour l'axe X)
df_weekly["dateSeance_day"] = df_weekly["dateSeance_day"].dt.to_timestamp()

# Garder True uniquement
df_weekly_true = df_weekly[df_weekly["repu_match_valide"] == True]

# Graphique
fig_weekly = px.bar(
    df_weekly_true,
    x="dateSeance_day",
    y="proportion",
    title="Évolution de la proportion des occurrences de la famille du mot 'République' par semaine",
    labels={"proportion": "% des occurences hebdomaire", "dateSeance_day": "Semaine"},
    template="plotly_white",
)

fig_weekly.show()

#### Par semaine sur corpus annualisé

In [11]:
# Choisir une année
annee = 2021

# Filtrer le DataFrame sur l'année choisie
df_annee = df[df["dateSeance_day"].dt.year == annee]

# Grouper par semaine
df_weekly = (
    df_annee.groupby(df["dateSeance_day"].dt.to_period("W"))["repu_match_valide"]
    .value_counts(normalize=True)
    .rename("proportion")
    .reset_index()
)

# Transformer la période en datetime (pour l'axe X)
df_weekly["dateSeance_day"] = df_weekly["dateSeance_day"].dt.to_timestamp()

# Garder True uniquement
df_weekly_true = df_weekly[df_weekly["repu_match_valide"] == True]

# aficher les 25 dates les plus fréquentes sous forme de tableau
table = df_weekly_true.sort_values("proportion", ascending=False).head(20)
table

   dateSeance_day  repu_match_valide  proportion
7      2021-02-01               True    0.164128
43     2021-06-28               True    0.133037
9      2021-02-08               True    0.081830
51     2021-09-06               True    0.042821
3      2021-01-18               True    0.039950
69     2021-11-15               True    0.038600
15     2021-03-08               True    0.038445
19     2021-03-22               True    0.032878
35     2021-05-31               True    0.032045
27     2021-05-03               True    0.031346
13     2021-03-01               True    0.029249
33     2021-05-24               True    0.029078
47     2021-07-12               True    0.028490
39     2021-06-14               True    0.027094
63     2021-10-25               True    0.025608
71     2021-11-22               True    0.023588
73     2021-11-29               True    0.023246
31     2021-05-17               True    0.021105
49     2021-07-19               True    0.020012
41     2021-06-21               True    0.019167

In [12]:
# Grouper par semaine
df_weekly = (
    df.groupby(df["dateSeance_day"].dt.to_period("W"))["repu_match_valide"]
    .value_counts(normalize=True)
    .rename("proportion")
    .reset_index()
)

# Transformer la période en datetime (pour l'axe X)
df_weekly["dateSeance_day"] = df_weekly["dateSeance_day"].dt.to_timestamp()

# Garder True uniquement
df_weekly_true = df_weekly[df_weekly["repu_match_valide"] == True]

# Choisir une année
annee = 2021

# Filtrer le DataFrame sur l'année choisie
df_annee_semaine = df_weekly_true[df_weekly_true["dateSeance_day"].dt.year == annee]

# Graphique
fig_annee_semaine = px.bar(
    df_annee_semaine,
    x="dateSeance_day",
    y="proportion",
    title="Proportion occurrences de la 'République' par semaine en 2024",
    labels={"proportion": "% des occurences mensualisées", "dateSeance_day": "Mois"},
    template="plotly_white",
)

fig_annee_semaine.show()

### Par mois

#### Par mois sur corpus intégral

In [13]:
# Grouper par mois
df_monthly = (
    df.groupby(df["dateSeance_day"].dt.to_period("M"))["repu_match_valide"]
    .value_counts(normalize=True)
    .rename("proportion")
    .reset_index()
)

# Transformer la période en datetime (pour l'axe X)
df_monthly["dateSeance_day"] = df_monthly["dateSeance_day"].dt.to_timestamp()

# Garder True uniquement
df_monthly_true = df_monthly[df_monthly["repu_match_valide"] == True]

# aficher les 10 mois les plus fréquents sous forme de tableau
table = df_monthly_true.sort_values("proportion", ascending=False).head(10)
table

    dateSeance_day  repu_match_valide  proportion
85      2021-02-01               True    0.089236
41      2019-02-01               True    0.052508
109     2022-03-01               True    0.052083
27      2018-07-01               True    0.050570
29      2018-08-01               True    0.041885
7       2017-09-01               True    0.040854
93      2021-06-01               True    0.039803
107     2022-02-01               True    0.039651
142     2023-12-01               True    0.037799
19      2018-03-01               True    0.036383

In [14]:
# Grouper par mois
df_monthly = (
    df.groupby(df["dateSeance_day"].dt.to_period("M"))["repu_match_valide"]
    .value_counts(normalize=True)
    .rename("proportion")
    .reset_index()
)

# Transformer la période en datetime (pour l'axe X)
df_monthly["dateSeance_day"] = df_monthly["dateSeance_day"].dt.to_timestamp()

# Garder True uniquement
df_monthly_true = df_monthly[df_monthly["repu_match_valide"] == True]

# Graphique
fig_monthly = px.bar(
    df_monthly_true,
    x="dateSeance_day",
    y="proportion",
    title="Proportion occurrences de la 'République' par mois",
    labels={"proportion": "% des occurences mensualisées", "dateSeance_day": "Mois"},
    template="plotly_white",
)

fig_monthly.show()

#### Par mois sur corpus annualisé

In [15]:
# Grouper par mois
df_monthly = (
    df.groupby(df["dateSeance_day"].dt.to_period("M"))["repu_match_valide"]
    .value_counts(normalize=True)
    .rename("proportion")
    .reset_index()
)

# Transformer la période en datetime (pour l'axe X)
df_monthly["dateSeance_day"] = df_monthly["dateSeance_day"].dt.to_timestamp()

# Garder True uniquement
df_monthly_true = df_monthly[df_monthly["repu_match_valide"] == True]

# Choisir une année
annee = 2021

# Filtrer le DataFrame sur l'année choisie
df_annee_mois = df_monthly_true[df_monthly_true["dateSeance_day"].dt.year == annee]

# aficher les 25 dates les plus fréquentes sous forme de tableau
table = df_annee_mois.sort_values("proportion", ascending=False).head(20)
table

    dateSeance_day  repu_match_valide  proportion
85      2021-02-01               True    0.089236
93      2021-06-01               True    0.039803
87      2021-03-01               True    0.025887
95      2021-07-01               True    0.025641
91      2021-05-01               True    0.023731
97      2021-09-01               True    0.020833
83      2021-01-01               True    0.019387
103     2021-12-01               True    0.018256
101     2021-11-01               True    0.016875
99      2021-10-01               True    0.013081
89      2021-04-01               True    0.011924

In [16]:
# Grouper par mois
df_monthly = (
    df.groupby(df["dateSeance_day"].dt.to_period("M"))["repu_match_valide"]
    .value_counts(normalize=True)
    .rename("proportion")
    .reset_index()
)

# Transformer la période en datetime (pour l'axe X)
df_monthly["dateSeance_day"] = df_monthly["dateSeance_day"].dt.to_timestamp()

# Garder True uniquement
df_monthly_true = df_monthly[df_monthly["repu_match_valide"] == True]

# Choisir une année
annee = 2021

# Filtrer le DataFrame sur l'année choisie
df_annee_mois = df_monthly_true[df_monthly_true["dateSeance_day"].dt.year == annee]

# Graphique
fig_annee_mois = px.bar(
    df_annee_mois,
    x="dateSeance_day",
    y="proportion",
    title="Proportion occurrences de la 'République' par mois en 2021",
    labels={"proportion": "% des occurences mensualisées", "dateSeance_day": "Mois"},
    template="plotly_white",
)

fig_annee_mois.show()

#### Par an

In [17]:
# Grouper par an
df_annee = (
    df.groupby(df["dateSeance_day"].dt.to_period("Y"))["repu_match_valide"]
    .value_counts(normalize=True)
    .rename("proportion")
    .reset_index()
)

# Transformer la période en datetime (pour l'axe X)
df_annee["dateSeance_day"] = df_annee["dateSeance_day"].dt.to_timestamp()

# Garder True uniquement
df_annee_true = df_annee[df_annee["repu_match_valide"] == True]

# aficher les 10 mois les plus fréquents sous forme de tableau
table = df_annee_true.sort_values("proportion", ascending=False).head(10)
table

   dateSeance_day  repu_match_valide  proportion
9      2021-01-01               True    0.030371
3      2018-01-01               True    0.021300
1      2017-01-01               True    0.019215
5      2019-01-01               True    0.019019
13     2023-01-01               True    0.018254
11     2022-01-01               True    0.017844
15     2024-01-01               True    0.016930
7      2020-01-01               True    0.015959

In [18]:
# Grouper par année
df_yearly = (
    df.groupby(df["dateSeance_day"].dt.year)["repu_match_valide"]
    .value_counts(normalize=True)
    .rename("proportion")
    .reset_index()
)

# Garder True uniquement
df_yearly_true = df_yearly[df_yearly["repu_match_valide"] == True]

# Graphique
fig_yearly = px.bar(
    df_yearly_true,
    x="dateSeance_day",
    y="proportion",
    title="Proportion occurrences de la 'République' par année",
    labels={"proportion": "% des occurences annualisées", "dateSeance_day": "Année"},
    template="plotly_white",
)

fig_yearly.show()

## Par groupes

### Sur total

In [19]:
# Compter le nombre de fois où chaque groupe parlementaire dit "République"
counts = (
    df.groupby("groupe_députés_affiliation")["repu_match_valide"]
    .agg(total_mentions="count", true_mentions=lambda x: (x == True).sum())
    .reset_index()
)

# Calcul de la proportion
counts["proportion_true"] = counts["true_mentions"] / counts["total_mentions"]

# Filtrer les orateurs avec au moins 10 mentions True
filtered = counts[counts["true_mentions"] >= 250]

# Trier par proportion décroissante et garder les 40 premiers
df_toppartis = filtered.sort_values("proportion_true", ascending=False).head(40).reset_index(drop=True)

# Graphique
fig_toppartis = px.bar(
    df_toppartis,
    x="groupe_députés_affiliation",
    y="proportion_true",
    title="Proportions des occurrences de la 'République' par groupe parlementaire (<250 occurrences)",
    labels={"groupe_députés_affiliation": "Groupe parlementaire", "proportion_true": "% 'République'"},
    template="plotly_white",
)

fig_toppartis.update_layout(xaxis_tickangle=-45)

fig_toppartis.show()
df_toppartis

  groupe_députés_affiliation  total_mentions  true_mentions  proportion_true
0                        GDR           42546           1159         0.027241
1                        ECO           13975            380         0.027191
2                        LFI           78975           2139         0.027085
3                        UDI           18682            482         0.025800
4                      SOC-A           43427           1020         0.023488
5                       LIOT           18387            414         0.022516
6                        DEM           39364            663         0.016843
7                         RN           28310            438         0.015472
8                        REN          131697           1991         0.015118
9                         LR          131134           1975         0.015061

In [20]:
# TODO : changer manuellement les couleurs des graphiques

def analyse_evolution_pourcentage(df,
                                  date_col="dateSeance_day",
                                  parti_col="groupe_députés_affiliation",
                                  match_col="repu_match_valide",
                                  min_true_mentions=500,
                                  top_n=5):

    # Calcul global des proportions par groupe
    counts = (
        df.groupby(parti_col)[match_col]
        .agg(total_mentions="count", true_mentions=lambda x: (x == True).sum())
        .reset_index()
    )

    # Ajouter la proportion globale
    counts["proportion_true"] = counts["true_mentions"] / counts["total_mentions"]

    # Filtrer les partis avec au moins min_true_mentions
    filtered = counts[counts["true_mentions"] >= min_true_mentions]

    # Sélectionner les top_n groupes selon la proportion
    top_partis = (
        filtered.sort_values("proportion_true", ascending=False)
        .head(top_n)[parti_col]
        .tolist()
    )

    # Filtrer les données pour ces groupes
    df_top = df[df[parti_col].isin(top_partis)].copy()

    # Calculer les stats annuelles : mentions totales et vraies
    df_grouped = (
        df_top.groupby([pd.Grouper(key=date_col, freq="Y"), parti_col])[match_col]
        .agg(total_mentions="count", true_mentions=lambda x: (x == True).sum())
        .reset_index()
    )

    # Ajouter la proportion annuelle (% d'utilisation)
    df_grouped["proportion_true"] = (
        df_grouped["true_mentions"] / df_grouped["total_mentions"]
    )

    # Extraire l'année pour affichage
    df_grouped["Année"] = df_grouped[date_col].dt.year

    # Tracer l'évolution du % dans le temps
    fig = px.line(
        df_grouped,
        x="Année",
        y="proportion_true",
        color=parti_col,
        markers=True,
        title=f"Évolution annuelle du % d'utilisation de la 'République' des {top_n} principaux groupes parlementaires (>{min_true_mentions} occurrences)",
        labels={
            "proportion_true": "% d'utilisation",
            parti_col: "Groupe parlementaire"
        }
    )

    fig.update_layout(
        xaxis=dict(dtick=1),
        hovermode="x unified",
        template="plotly_white",
        legend_title_text="Groupe",
        yaxis_tickformat=".0%",
    )

    fig.show()

In [21]:
analyse_evolution_pourcentage(df)

/var/folders/gc/0c_w194n61ggswq_j8v40mj80000gn/T/ipykernel_3656/1209360484.py:35: FutureWarning:

'Y' is deprecated and will be removed in a future version, please use 'YE' instead.

### Par période

In [22]:
def top_parti_periodique(df, periode=None, annee=None, semaine=None, jour=None, 
                            date_debut=None, date_fin=None, jours=None,
                            colonne_condition="repu_match_valide",
                            seuil_min_true=None, top_n=20):

    # --- Filtrage selon la période ---
    if periode == "annee":
        if annee is None:
            raise ValueError("Il faut préciser l'année pour periode='annee'")
        df_filtered = df[df["dateSeance_day"].dt.year == annee]
        titre = f"Parti mobilisant en % le plus la 'République' en {annee} à l'Assemblée Nationale (Seuil de {seuil_min_true} occurences)"

    elif periode == "semaine":
        if annee is None or semaine is None:
            raise ValueError("Il faut préciser l'année et la semaine pour periode='semaine'")
        df_filtered = df[
            (df["dateSeance_day"].dt.isocalendar().year == annee) &
            (df["dateSeance_day"].dt.isocalendar().week == semaine)
        ]
        titre = f"Parti mobilisant en % le plus la 'République' la {semaine} semaine {annee} à l'Assemblée Nationale (Seuil de {seuil_min_true})"

    elif periode == "jour":
        if jour is None:
            raise ValueError("Il faut préciser la date pour periode='jour'")
        jour_dt = pd.to_datetime(jour).date()
        df_filtered = df[df["dateSeance_day"].dt.date == jour_dt]
        titre = f"Parti mobilisant le plus en % la 'République' le {jour_dt} (Seuil de {seuil_min_true} occurences)"

    elif periode == "intervalle":
        if date_debut is None or date_fin is None:
            raise ValueError("Il faut préciser date_debut et date_fin pour periode='intervalle'")
        debut = pd.to_datetime(date_debut)
        fin = pd.to_datetime(date_fin)
        df_filtered = df[(df["dateSeance_day"] >= debut) & (df["dateSeance_day"] <= fin)]
        titre = f"Parti mobilisant le plus en % la 'République' du {debut.date()} au {fin.date()} (Seuil de {seuil_min_true} occurences)"

    elif periode == "jours":
        if jours is None or not isinstance(jours, (list, tuple)):
            raise ValueError("Il faut fournir une liste de dates pour periode='jours'")
        jours_dt = [pd.to_datetime(j).date() for j in jours]
        df_filtered = df[df["dateSeance_day"].dt.date.isin(jours_dt)]
        titre = f"Parti mobilisant le plus la 'République' en % lors de X évènement (Seuil de {seuil_min_true} occurences)"

    else:
        raise ValueError("periode doit être 'annee', 'semaine', 'jour', 'intervalle' ou 'jours'")

    # --- Comptage des occurrences ---
    counts = (
        df_filtered.groupby("groupe_députés_affiliation")[colonne_condition]
        .agg(total_mentions="count", true_mentions=lambda x: (x == True).sum())
        .reset_index()
    )
    counts["proportion_true"] = counts["true_mentions"] / counts["total_mentions"]

    # --- Filtrage par seuil ---
    filtered = counts[counts["true_mentions"] >= seuil_min_true]

    # --- Trier par proportion décroissante et garder top_n ---
    df_top = (
        filtered.sort_values("proportion_true", ascending=False)
        .head(top_n)
        .reset_index(drop=True)
    )

    # --- Graphique ---
    fig = px.bar(
        df_top,
        x="groupe_députés_affiliation",
        y="proportion_true",
        hover_data=["true_mentions", "total_mentions"],
        title=titre,
        template="plotly_white",
    )
    fig.update_layout(xaxis_tickangle=-45, showlegend=False, yaxis_title="Proportion des interventions totales", xaxis_title="Groupes parlementaires")
    fig.show()

    return df_top

In [23]:
# Top partis en % par année
top_parti_periodique(df, periode="annee", annee=2017, seuil_min_true=25)

  groupe_députés_affiliation  total_mentions  true_mentions  proportion_true
0                        LFI            5704            234         0.041024
1                        GDR            3679            112         0.030443
2                         RN             908             27         0.029736
3                      SOC-A            4463             75         0.016805
4                        UDI            3193             53         0.016599
5                        DEM            2039             32         0.015694
6                        REN            9996            154         0.015406
7                         LR           12714            168         0.013214

In [24]:
# Top 10 orateurs sur la semaine X de X
top_parti_periodique(df, periode="semaine", annee=2021, semaine=6, seuil_min_true=20)

  groupe_députés_affiliation  total_mentions  true_mentions  proportion_true
0                        LFI             252             34         0.134921
1                        UDI             197             23         0.116751
2                        REN            1355            113         0.083395
3                        DEM             387             29         0.074935
4                         LR            1124             56         0.049822

In [25]:
# Top  partis en % (tel jour) le X 
top_parti_periodique(df, periode="jour", jour="2021-02-01",seuil_min_true=10)

  groupe_députés_affiliation  total_mentions  true_mentions  proportion_true
0                       LIOT              24             15         0.625000
1                        REN              63             21         0.333333
2                        LFI             111             24         0.216216

In [26]:
# Top partis en % (sur telle période) du 1er au 16 février 2021
top_parti_periodique(df, periode="intervalle", date_debut="2021-02-01", date_fin="2021-02-16", seuil_min_true=20)

  groupe_députés_affiliation  total_mentions  true_mentions  proportion_true
0                     AGIR-E             150             39         0.260000
1                      SOC-A             344             49         0.142442
2                        GDR             430             61         0.141860
3                        UDI             323             45         0.139319
4                        LFI             783             94         0.120051
5                        REN            2377            277         0.116533
6                       LIOT             375             37         0.098667
7                        DEM             780             73         0.093590
8                         LR            2167            151         0.069682

#### Évolutions par période

In [ ]:
# TODO : changer manuellement les couleurs des graphiques

def groupes_evolutions_périodes(df,
                                  date_col="dateSeance_day",
                                  parti_col="groupe_députés_affiliation",
                                  match_col="repu_match_valide",
                                  min_true_mentions=100,
                                  top_n=7,
                                  start_year=2021,
                                  end_year=2021):

    # Filtrer par période si spécifiée
    if start_year or end_year:
        mask = pd.Series(True, index=df.index)
        if start_year:
            mask &= df[date_col].dt.year >= start_year
        if end_year:
            mask &= df[date_col].dt.year <= end_year
        df = df.loc[mask].copy()

    # Calcul global des proportions par groupe
    counts = (
        df.groupby(parti_col)[match_col]
        .agg(total_mentions="count", true_mentions=lambda x: (x == True).sum())
        .reset_index()
    )

    counts["proportion_true"] = counts["true_mentions"] / counts["total_mentions"]

    # Filtrer les groupes pertinents
    filtered = counts[counts["true_mentions"] >= min_true_mentions]

    # Sélectionner les top groupes selon la proportion
    top_partis = (
        filtered.sort_values("proportion_true", ascending=False)
        .head(top_n)[parti_col]
        .tolist()
    )

    # Filtrer les données pour ces groupes
    df_top = df[df[parti_col].isin(top_partis)].copy()

    # Calcul annuel des proportions
    df_grouped = (
        df_top.groupby([pd.Grouper(key=date_col, freq="M"), parti_col])[match_col]
        .agg(total_mentions="count", true_mentions=lambda x: (x == True).sum())
        .reset_index()
    )

    df_grouped["proportion_true"] = df_grouped["true_mentions"] / df_grouped["total_mentions"]
    df_grouped["Année"] = df_grouped[date_col].dt.year
    df_grouped["Mois"] = df_grouped[date_col].dt.strftime("%Y-%m")

    # Tracé du graphique (% d’utilisation par année)
    fig = px.line(
        df_grouped,
        x="Mois",
        y="proportion_true",
        color=parti_col,
        markers=True,
        title=(
            f"Évolution mensuelle du % d'utilisation du mot 'République' "
            f"(Des {top_n} principaux groupes parlementaires, {start_year or df_grouped['Année'].min()}–{end_year or df_grouped['Année'].max()})"
        ),
        labels={"proportion_true": "% d'utilisation", parti_col: "Groupe parlementaire"}
    )

    fig.update_layout(
        xaxis=dict(dtick="M1", tickangle=45),
        hovermode="x unified",
        template="plotly_white",
        legend_title_text="Groupe",
        yaxis_tickformat=".0%"
    )

    fig.show()

In [67]:
groupes_evolutions_périodes(df)

/var/folders/gc/0c_w194n61ggswq_j8v40mj80000gn/T/ipykernel_3656/1640926553.py:45: FutureWarning:

'M' is deprecated and will be removed in a future version, please use 'ME' instead.

,UID,SeanceRef,SessionRef,dateSeance,dateSeanceJour,numSeanceJour,numSeance,typeAssemblee,legislature,session,...,scoreMajorite,dateMaj,dateSeance_ts,groupe_députés_affiliation,groupe&gvt_affiliation,groupe_all_affiliation,Texte_clean,repu_match_valide,match_republi_simple,dateSeance_day
2184,CRSANR5L15S2022O1N006,RUANR5L15S2021IDS23226,SCR5A2021O1,20211007150000000,jeudi 07 octobre 2021,2,6,AN,15,Session ordinaire 2021-2022,...,0.000,2025-09-26,2021-10-07,DEM,DEM,DEM,"Nous ne sommes pas d'accord, et nous l'assumons !",False,False,2021-10-07
2189,CRSANR5L15S2022O1N006,RUANR5L15S2021IDS23226,SCR5A2021O1,20211007150000000,jeudi 07 octobre 2021,2,6,AN,15,Session ordinaire 2021-2022,...,0.000,2025-09-26,2021-10-07,DEM,DEM,DEM,Vous pensez que Mme Dupont ne maîtrise pas par...,False,False,2021-10-07
2193,CRSANR5L15S2022O1N006,RUANR5L15S2021IDS23226,SCR5A2021O1,20211007150000000,jeudi 07 octobre 2021,2,6,AN,15,Session ordinaire 2021-2022,...,0.000,2025-09-26,2021-10-07,DEM,DEM,DEM,"Ça, c'est une remarque de haut niveau !",False,False,2021-10-07
2196,CRSANR5L15S2022O1N006,RUANR5L15S2021IDS23226,SCR5A2021O1,20211007150000000,jeudi 07 octobre 2021,2,6,AN,15,Session ordinaire 2021-2022,...,0.427,2025-09-26,2021-10-07,SOC-A,SOC-A,SOC-A,"Madame la secrétaire d'État, puis-je me permet...",False,False,2021-10-07
2198,CRSANR5L15S2022O1N006,RUANR5L15S2021IDS23226,SCR5A2021O1,20211007150000000,jeudi 07 octobre 2021,2,6,AN,15,Session ordinaire 2021-2022,...,0.427,2025-09-26,2021-10-07,SOC-A,SOC-A,SOC-A,…en particulier lorsqu'il s'agit d'un enfant :...,False,False,2021-10-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
461991,CRSANR5L15S2021O1N229,RUANR5L15S2021IDS24041,SCR5A2021O1,20210402210000000,vendredi 02 avril 2021,3,229,AN,15,session ordinaire 2020-2021,...,0.000,2025-09-26,2021-04-02,GDR,GDR,GDR,"Quand vous êtes détendue, je vous comprends mi...",False,False,2021-04-02
461996,CRSANR5L15S2021O1N229,RUANR5L15S2021IDS24041,SCR5A2021O1,20210402210000000,vendredi 02 avril 2021,3,229,AN,15,session ordinaire 2020-2021,...,0.966,2025-09-26,2021-04-02,DEM,DEM,DEM,C'était bien tenté !,False,False,2021-04-02
462004,CRSANR5L15S2021O1N229,RUANR5L15S2021IDS24041,SCR5A2021O1,20210402210000000,vendredi 02 avril 2021,3,229,AN,15,session ordinaire 2020-2021,...,0.852,2025-09-26,2021-04-02,DEM,DEM,DEM,Il vise à favoriser le développement des entre...,False,False,2021-04-02
462007,CRSANR5L15S2021O1N229,RUANR5L15S2021IDS24041,SCR5A2021O1,20210402210000000,vendredi 02 avril 2021,3,229,AN,15,session ordinaire 2020-2021,...,0.852,2025-09-26,2021-04-02,DEM,DEM,DEM,Le présent amendement vise à favoriser le déve...,False,False,2021-04-02
462014,CRSANR5L15S2021O1N229,RUANR5L15S2021IDS24041,SCR5A2021O1,20210402210000000,vendredi 02 avril 2021,3,229,AN,15,session ordinaire 2020-2021,...,0.401,2025-09-26,2021-04-02,LIOT,LIOT,LIOT,Au vu de l'objectif affiché dans l'exposé somm...,False,False,2021-04-02

## Par personnel politique / individuellement

***À garder en tête au moment de l'analyse et interprétation des résultats, l'analyse en % dépend de notre unité de mesure (nombre de prises de paroles avec ou sans interruption, phrases). On ne peut pas mesurer en durée de l'intervention ou nombre de mots pour l'intervention donc il ne s'agit pas à proprement parlé d'un % en termes de temps de parole (= un artéfact statistique dont il serait intéressant de comparer les mesures).***

### Les principaux orateurs sur la période

In [49]:
# Compter le nombre de fois où chaque orateur dit "République"
counts = (
    df.groupby("nom_orateur_clean")["repu_match_valide"]
    .agg(total_mentions="count", true_mentions=lambda x: (x == True).sum())
    .reset_index()
)

# Calcul de la proportion
counts["proportion_true"] = counts["true_mentions"] / counts["total_mentions"]

# Filtrer les orateurs avec au moins 10 mentions True
filtered = counts[counts["true_mentions"] >= 65]

# Trier par proportion décroissante et garder les 40 premiers
df_top20 = filtered.sort_values("proportion_true", ascending=False).head(20).reset_index(drop=True)

# Graphique
fig_top20 = px.bar(
    df_top20,
    x="nom_orateur_clean",
    y="proportion_true",
    title="Top 20 orateurs par proportion de mentions de 'République'",
    labels={"nom_orateur_clean": "Personnel politique", "proportion_true": "% 'République'"},
    template="plotly_white",
)

fig_top20.update_layout(xaxis_tickangle=-45)

fig_top20.show()
df_top20

             nom_orateur_clean  total_mentions  true_mentions  proportion_true
0             M. Éric Poulliat             409             69         0.168704
1         M. Guillaume Larrivé             663             72         0.108597
2               M. Éric Ciotti            1721            173         0.100523
3         Mme Marlène Schiappa            1290            128         0.099225
4      M. Jean-Michel Blanquer            2160            180         0.083333
5   M. Jean-Christophe Lagarde            1605            117         0.072897
6          M. Édouard Philippe            2326            152         0.065348
7           M. Alexis Corbière            4324            278         0.064292
8       M. Christophe Castaner            1206             75         0.062189
9            M. Benjamin Lucas            3049            183         0.060020
10          M. Gérald Darmanin            8452            470         0.055608
11       M. Jean-Luc Mélenchon            4101            219         0.053402
12         M. Dominique Potier            2717            131         0.048215
13        M. Sébastien Lecornu            2476            117         0.047254
14          M. Bastien Lachaud            2525            118         0.046733
15          Mme Mathilde Panot            3700            169         0.045676
16         M. Antoine Léaument            2428            109         0.044893
17             M. Stéphane Peu            3902            171         0.043824
18            M. Boris Vallaud            2836             99         0.034908
19          M. Aurélien Pradié            2153             74         0.034371

### Évolutions

In [62]:
# TODO : changer manuellement les couleurs des graphiques

def evolution_personnel_pourcentage(df,
                                  date_col="dateSeance_day",
                                  personnel_col="nom_orateur_clean",
                                  match_col="repu_match_valide",
                                  min_true_mentions=150,
                                  top_n=6):

    # Calcul global des proportions par groupe
    counts = (
        df.groupby(personnel_col)[match_col]
        .agg(total_mentions="count", true_mentions=lambda x: (x == True).sum())
        .reset_index()
    )

    # Ajouter la proportion globale
    counts["proportion_true"] = counts["true_mentions"] / counts["total_mentions"]

    # Filtrer les partis avec au moins min_true_mentions
    filtered = counts[counts["true_mentions"] >= min_true_mentions]

    # Sélectionner les top_n groupes selon la proportion
    top_personnel = (
        filtered.sort_values("proportion_true", ascending=False)
        .head(top_n)[personnel_col]
        .tolist()
    )

    # Filtrer les données pour ces groupes
    df_top = df[df[personnel_col].isin(top_personnel)].copy()

    # Calculer les stats annuelles : mentions totales et vraies
    df_grouped = (
        df_top.groupby([pd.Grouper(key=date_col, freq="Y"), personnel_col])[match_col]
        .agg(total_mentions="count", true_mentions=lambda x: (x == True).sum())
        .reset_index()
    )

    # Ajouter la proportion annuelle (% d'utilisation)
    df_grouped["proportion_true"] = (
        df_grouped["true_mentions"] / df_grouped["total_mentions"]
    )

    # Extraire l'année pour affichage
    df_grouped["Année"] = df_grouped[date_col].dt.year

    # Tracer l'évolution du % dans le temps
    fig = px.line(
        df_grouped,
        x="Année",
        y="proportion_true",
        color=personnel_col,
        markers=True,
        title=f"Évolution annuelle du % d'utilisation de la 'République' des {top_n} principaux personnels politiques (>{min_true_mentions} occurrences)",
        labels={
            "proportion_true": "% d'utilisation",
            personnel_col: "Groupe parlementaire"
        }
    )

    fig.update_layout(
        xaxis=dict(dtick=1),
        hovermode="x unified",
        template="plotly_white",
        legend_title_text="Groupe",
        yaxis_tickformat=".0%",
    )

    fig.show()

In [63]:
evolution_personnel_pourcentage(df)

/var/folders/gc/0c_w194n61ggswq_j8v40mj80000gn/T/ipykernel_3656/434538138.py:35: FutureWarning:

'Y' is deprecated and will be removed in a future version, please use 'YE' instead.

In [30]:
df_16e = df[df["legislature"]== 16]
df_15e = df[df["legislature"]== 15]

In [31]:
# Compter le nombre de fois où chaque orateur dit "République"
counts = (
    df_16e.groupby("nom_orateur_clean")["repu_match_valide"]
    .agg(total_mentions="count", true_mentions=lambda x: (x == True).sum())
    .reset_index()
)

# Calcul de la proportion
counts["proportion_true"] = counts["true_mentions"] / counts["total_mentions"]

# Filtrer les orateurs avec au moins 10 mentions True
filtered = counts[counts["true_mentions"] >= 40]

# Trier par proportion décroissante et garder les 40 premiers
df16_top20 = filtered.sort_values("proportion_true", ascending=False).head(40).reset_index(drop=True)

# Graphique
fig16_top20 = px.bar(
    df16_top20,
    x="nom_orateur_clean",
    y="proportion_true",
    title="Top 20 orateurs par proportion de mentions de 'République > 40, 16e législature'",
    labels={"nom_orateur_clean": "Personnel politique", "proportion_true": "% 'République'"},
    template="plotly_white",
)

fig16_top20.update_layout(xaxis_tickangle=-45)

fig16_top20.show()
df16_top20

        nom_orateur_clean  total_mentions  true_mentions  proportion_true
0      M. Gérald Darmanin            2140            165         0.077103
1     Mme Élisabeth Borne            1947            129         0.066256
2       M. Benjamin Lucas            3049            183         0.060020
3        Mme Aurore Bergé             789             40         0.050697
4      Mme Mathilde Panot            1098             55         0.050091
5     M. Antoine Léaument            2428            109         0.044893
6    M. Sébastien Lecornu            1173             42         0.035806
7        M. Gabriel Attal            3003             62         0.020646
8  M. Éric Dupond-Moretti            3332             60         0.018007

In [32]:
# Compter le nombre de fois où chaque orateur dit "République"
counts = (
    df_15e.groupby("nom_orateur_clean")["repu_match_valide"]
    .agg(total_mentions="count", true_mentions=lambda x: (x == True).sum())
    .reset_index()
)

# Calcul de la proportion
counts["proportion_true"] = counts["true_mentions"] / counts["total_mentions"]

# Filtrer les orateurs avec au moins 10 mentions True
filtered = counts[counts["true_mentions"] >= 100]

# Trier par proportion décroissante et garder les 40 premiers
df15_top20 = filtered.sort_values("proportion_true", ascending=False).head(40).reset_index(drop=True)

# Graphique
fig15_top20 = px.bar(
    df15_top20,
    x="nom_orateur_clean",
    y="proportion_true",
    title="Top 20 orateurs par proportion de mentions de 'République > 40 15e législature'",
    labels={"nom_orateur_clean": "Personnel politique", "proportion_true": "% 'République'"},
    template="plotly_white",
)

fig15_top20.update_layout(xaxis_tickangle=-45)

fig15_top20.show()
df15_top20

             nom_orateur_clean  total_mentions  true_mentions  proportion_true
0               M. Éric Ciotti            1434            153         0.106695
1         Mme Marlène Schiappa            1281            128         0.099922
2      M. Jean-Michel Blanquer            2160            180         0.083333
3   M. Jean-Christophe Lagarde            1605            117         0.072897
4           M. Alexis Corbière            3447            246         0.071366
5          M. Édouard Philippe            2326            152         0.065348
6        M. Jean-Luc Mélenchon            4101            219         0.053402
7          M. Dominique Potier            1953            103         0.052739
8           M. Gérald Darmanin            6312            305         0.048321
9              M. Stéphane Peu            3371            156         0.046277
10          Mme Mathilde Panot            2602            114         0.043812
11          M. Sébastien Jumel            5519            206         0.037326
12            M. Éric Coquerel            4297            154         0.035839
13        M. Philippe Gosselin            3877            126         0.032499
14           Mme Danièle Obono            4394            129         0.029358
15       M. Pierre Dharréville            3825            100         0.026144
16           M. Ugo Bernalicis            6764            127         0.018776

### Les principaux orateurs par années/semaines/séances

In [64]:
def top_orateurs_periodique(df, periode="annee", annee=None, semaine=None, jour=None, 
                            date_debut=None, date_fin=None, jours=None,
                            colonne_condition="repu_match_valide",
                            seuil_min_true=None, top_n=20):

    # --- Filtrage selon la période ---
    if periode == "annee":
        if annee is None:
            raise ValueError("Il faut préciser l'année pour periode='annee'")
        df_filtered = df[df["dateSeance_day"].dt.year == annee]
        titre = f"Personnel politique mobilisant en % le plus la 'République' en {annee} à l'Assemblée Nationale (Seuil de {seuil_min_true} occurences)"

    elif periode == "semaine":
        if annee is None or semaine is None:
            raise ValueError("Il faut préciser l'année et la semaine pour periode='semaine'")
        df_filtered = df[
            (df["dateSeance_day"].dt.isocalendar().year == annee) &
            (df["dateSeance_day"].dt.isocalendar().week == semaine)
        ]
        titre = f"Personnel politique mobilisant en % le plus la 'République' la {semaine} semaine {annee} à l'Assemblée Nationale (Seuil de {seuil_min_true})"

    elif periode == "jour":
        if jour is None:
            raise ValueError("Il faut préciser la date pour periode='jour'")
        jour_dt = pd.to_datetime(jour).date()
        df_filtered = df[df["dateSeance_day"].dt.date == jour_dt]
        titre = f"Personnel politique mobilisant le plus en % la 'République' le {jour_dt} (Seuil de {seuil_min_true} occurences)"

    elif periode == "intervalle":
        if date_debut is None or date_fin is None:
            raise ValueError("Il faut préciser date_debut et date_fin pour periode='intervalle'")
        debut = pd.to_datetime(date_debut)
        fin = pd.to_datetime(date_fin)
        df_filtered = df[(df["dateSeance_day"] >= debut) & (df["dateSeance_day"] <= fin)]
        titre = f"Personnel politique mobilisant le plus en % la 'République' du {debut.date()} au {fin.date()} (Seuil de {seuil_min_true} occurences)"

    elif periode == "jours":
        if jours is None or not isinstance(jours, (list, tuple)):
            raise ValueError("Il faut fournir une liste de dates pour periode='jours'")
        jours_dt = [pd.to_datetime(j).date() for j in jours]
        df_filtered = df[df["dateSeance_day"].dt.date.isin(jours_dt)]
        titre = f"Personnel politique mobilisant le plus la 'République' en % lors de X évènement (Seuil de {seuil_min_true} occurences)"

    else:
        raise ValueError("periode doit être 'annee', 'semaine', 'jour', 'intervalle' ou 'jours'")

    # --- Comptage des occurrences ---
    counts = (
        df_filtered.groupby("nom_orateur_clean")[colonne_condition]
        .agg(total_mentions="count", true_mentions=lambda x: (x == True).sum())
        .reset_index()
    )
    counts["proportion_true"] = counts["true_mentions"] / counts["total_mentions"]

    # --- Filtrage par seuil ---
    filtered = counts[counts["true_mentions"] >= seuil_min_true]

    # --- Trier par proportion décroissante et garder top_n ---
    df_top = (
        filtered.sort_values("proportion_true", ascending=False)
        .head(top_n)
        .reset_index(drop=True)
    )

    # --- Graphique ---
    fig = px.bar(
        df_top,
        x="nom_orateur_clean",
        y="proportion_true",
        hover_data=["true_mentions", "total_mentions"],
        title=titre,
        template="plotly_white",
    )
    fig.update_layout(xaxis_tickangle=-45, showlegend=False, yaxis_title="Proportion des interventions totales", xaxis_title="Personnel politique")
    fig.show()

    return df_top

In [77]:
# Top 10 orateurs en % par année
top_orateurs_periodique(df, periode="annee", annee=2024, seuil_min_true=20)

     nom_orateur_clean  total_mentions  true_mentions  proportion_true
0   M. Gérald Darmanin             334             33         0.098802
1  M. Antoine Léaument             449             24         0.053452
2  M. Dominique Potier             411             20         0.048662
3    M. Benjamin Lucas             586             28         0.047782
4     M. Gabriel Attal             811             35         0.043157

In [35]:
# Top 10 orateurs sur la semaine X de X
top_orateurs_periodique(df, periode="semaine", annee=2021, semaine=6, seuil_min_true=10)

            nom_orateur_clean  total_mentions  true_mentions  proportion_true
0          M. Gérald Darmanin             134             31         0.231343
1         M. François de Rugy              58             11         0.189655
2  M. Jean-Christophe Lagarde              90             16         0.177778
3          M. Alexis Corbière             152             25         0.164474
4     M. Jean-Michel Blanquer             151             24         0.158940
5            M. Xavier Breton              67             10         0.149254
6           Mme Anne Brugnera             282             17         0.060284

In [36]:
# Top 10 orateurs en % (tel jour) le X 
top_orateurs_periodique(df, periode="jour", jour="2021-02-01", seuil_min_true=10)

       nom_orateur_clean  total_mentions  true_mentions  proportion_true
0     M. Gérald Darmanin              27             11         0.407407
1     M. Alexis Corbière              37             11         0.297297
2  M. Jean-Luc Mélenchon              61             11         0.180328

In [37]:
# Top 10 orateurs en % (sur telle période) du 1er au 16 février 2021
top_orateurs_periodique(df, periode="intervalle", date_debut="2021-02-01", date_fin="2021-02-16", seuil_min_true=10)

             nom_orateur_clean  total_mentions  true_mentions  proportion_true
0     M. Pierre-Yves Bournazel              53             19         0.358491
1       M. Guillaume Vuilletet              50             15         0.300000
2             M. Éric Poulliat             162             41         0.253086
3            M. Francis Chouat              47             11         0.234043
4             M. Xavier Breton             120             28         0.233333
5          M. François de Rugy             174             39         0.224138
6           M. Gérald Darmanin             472            103         0.218220
7   M. Jean-Christophe Lagarde             167             35         0.209581
8             M. Boris Vallaud             133             26         0.195489
9      M. Jean-Michel Blanquer             165             26         0.157576
10          M. Alexis Corbière             357             56         0.156863
11              M. Éric Ciotti              80             12         0.150000
12       M. Pierre Dharréville              98             14         0.142857
13        Mme Marlène Schiappa             325             46         0.141538
14               M. Éric Diard              85             12         0.141176
15            M. Éric Coquerel              72             10         0.138889
16       M. Jean-Luc Mélenchon             102             14         0.137255
17         M. François Pupponi             132             16         0.121212
18             M. Stéphane Peu              95             11         0.115789
19       M. Charles de Courson             207             22         0.106280

In [38]:
# Top 10 orateurs en % sur des jours spécifiques
top_orateurs_periodique(df, periode="jours", jours=["2021-02-01", "2021-02-02", "2021-02-03", "2021-02-4", "2021-02-05"], seuil_min_true=10)

             nom_orateur_clean  total_mentions  true_mentions  proportion_true
0        M. Pierre Dharréville              33             13         0.393939
1             M. Éric Poulliat              96             35         0.364583
2             M. Xavier Breton              53             18         0.339623
3         Mme Marlène Schiappa             117             39         0.333333
4   M. Jean-Christophe Lagarde              77             19         0.246753
5          M. François de Rugy             116             28         0.241379
6             M. Boris Vallaud              88             21         0.238636
7           M. Gérald Darmanin             333             70         0.210210
8        M. Charles de Courson              72             14         0.194444
9               M. Éric Ciotti              68             12         0.176471
10          M. Alexis Corbière             194             29         0.149485
11       M. Jean-Luc Mélenchon              98             14         0.142857
12           M. Florent Boudié             150             18         0.120000
13    Mme Laurence Vichnievsky             163             12         0.073620

#### Analyse discussion du projet de loi séparatisme

In [39]:
# Top 10 orateurs lors de la 1ère discussion du projet de loi séparatisme 
top_orateurs_periodique(df, periode="jours", jours=["2021-02-01", "2021-02-02", "2021-02-03", "2021-02-04", "2021-02-05", "2021-02-08", "2021-02-10", "2021-02-11", "2021-02-12", "2021-02-13", "2021-02-16"], seuil_min_true=10)

             nom_orateur_clean  total_mentions  true_mentions  proportion_true
0     M. Pierre-Yves Bournazel              49             19         0.387755
1       M. Guillaume Vuilletet              50             15         0.300000
2             M. Éric Poulliat             162             41         0.253086
3            M. Francis Chouat              47             11         0.234043
4             M. Xavier Breton             120             28         0.233333
5   M. Jean-Christophe Lagarde             150             35         0.233333
6        M. Pierre Dharréville              60             14         0.233333
7          M. François de Rugy             174             39         0.224138
8           M. Gérald Darmanin             469            103         0.219616
9             M. Boris Vallaud             133             26         0.195489
10        Mme Marlène Schiappa             282             46         0.163121
11     M. Jean-Michel Blanquer             154             25         0.162338
12          M. Alexis Corbière             355             56         0.157746
13              M. Éric Ciotti              80             12         0.150000
14       M. Jean-Luc Mélenchon              98             14         0.142857
15               M. Éric Diard              85             12         0.141176
16            M. Éric Coquerel              72             10         0.138889
17             M. Stéphane Peu              89             11         0.123596
18         M. François Pupponi             132             16         0.121212
19       M. Charles de Courson             207             22         0.106280

In [40]:
# Top 10 orateurs en % lors des discussions du projet de loi séparatisme 
top_orateurs_periodique(df, periode="jours", jours=["2021-02-01", "2021-02-02", "2021-02-03", "2021-02-04", "2021-02-05", "2021-02-08", "2021-02-10", "2021-02-11", "2021-02-12", "2021-02-13", "2021-02-16", "2021-06-28", "2021-06-29", "2021-06-30", "2021-07-01", "2021-01-23"], seuil_min_true=10)

             nom_orateur_clean  total_mentions  true_mentions  proportion_true
0     M. Pierre-Yves Bournazel              54             22         0.407407
1          Mme Lamia El Aaraje              32             11         0.343750
2             M. Alain Bruneel              61             20         0.327869
3       M. Guillaume Vuilletet              76             20         0.263158
4             M. Éric Poulliat             204             53         0.259804
5            M. Francis Chouat              67             16         0.238806
6   M. Jean-Christophe Lagarde             150             35         0.233333
7           M. Gérald Darmanin             480            104         0.216667
8      Mme Marie-George Buffet              67             14         0.208955
9          M. François de Rugy             229             47         0.205240
10       M. Pierre Dharréville              74             15         0.202703
11            M. Xavier Breton             149             30         0.201342
12       Mme Cécile Untermaier              57             11         0.192982
13            M. Boris Vallaud             137             26         0.189781
14          M. Alexis Corbière             477             84         0.176101
15            M. Éric Coquerel             118             20         0.169492
16              M. Éric Ciotti             118             19         0.161017
17     M. Jean-Michel Blanquer             174             28         0.160920
18       M. Jean-Luc Mélenchon             121             19         0.157025
19               M. Éric Diard             144             21         0.145833

In [41]:
# Top 10 orateurs en % lors de la deuxième phase de discussion post débat Sénat 
top_orateurs_periodique(df, periode="jours", jours=["2021-06-28", "2021-06-29", "2021-06-30", "2021-07-01", "2021-01-23"], seuil_min_true=10)

     nom_orateur_clean  total_mentions  true_mentions  proportion_true
0     M. Alain Bruneel              28             12         0.428571
1  Mme Lamia El Aaraje              32             11         0.343750
2     M. Éric Poulliat              42             12         0.285714
3     M. Julien Ravier              54             14         0.259259
4   M. Alexis Corbière             122             28         0.229508
5     M. Éric Coquerel              46             10         0.217391

### Évolution dans le temps de la fréquence d'utilisation du top X de personnels politiques

In [ ]:
# REPRENDRE ICI

In [42]:
def stats_orateur_proportion(df, orateur, periode="semaine", colonne_condition="repu_match_valide"):
  
    # Filtrer sur l'orateur choisi
    df_orateur = df[df["nom_orateur_clean"] == orateur].copy()
    if df_orateur.empty:
        raise ValueError(f"Aucune donnée trouvée pour l'orateur : {orateur}")

    # Définir la granularité
    if periode == "semaine":
        df_orateur["periode"] = (
            df_orateur["dateSeance_day"].dt.isocalendar().year.astype(str)
            + "-W"
            + df_orateur["dateSeance_day"].dt.isocalendar().week.astype(str)
        )
    elif periode == "mois":
        df_orateur["periode"] = df_orateur["dateSeance_day"].dt.to_period("M").astype(str)
    elif periode == "annee":
        df_orateur["periode"] = df_orateur["dateSeance_day"].dt.year.astype(str)
    else:
        raise ValueError("periode doit être 'semaine', 'mois' ou 'annee'")

    # Compter occurrences par période (total et True)
    df_counts = (
        df_orateur.groupby("periode")[colonne_condition]
        .agg(total_mentions="count", true_mentions=lambda x: (x == True).sum())
        .reset_index()
    )

    # Proportion de True
    df_counts["proportion_true"] = df_counts["true_mentions"] / df_counts["total_mentions"]

    # Moyenne et médiane des occurrences
    moyenne_occ = df_counts["total_mentions"].mean()
    mediane_occ = df_counts["total_mentions"].median()

    # Moyenne et médiane des proportions
    moyenne_prop = df_counts["proportion_true"].mean()
    mediane_prop = df_counts["proportion_true"].median()

    return {
        "moyenne_occurrences": moyenne_occ,
        "mediane_occurrences": mediane_occ,
        "moyenne_proportion": moyenne_prop,
        "mediane_proportion": mediane_prop,
        "df_counts": df_counts,
    }

In [43]:
# Définir la personne recherchée 
orateur = "M. Gérald Darmanin"

# Statistiques hebdomadaires sur "République"
stats = stats_orateur_proportion(df, orateur, periode="annee", colonne_condition="repu_match_valide")

print(f"{orateur} - Moyenne/semaine (occurrences) : {stats['moyenne_occurrences']:.2f}")
print(f"{orateur} - Médiane/semaine (occurrences) : {stats['mediane_occurrences']}")
print(f"{orateur} - Moyenne/semaine (proportion)  : {stats['moyenne_proportion']:.2f}")
print(f"{orateur} - Médiane/semaine (proportion)  : {stats['mediane_proportion']:.2f}")

# Voir le détail par période
print(stats["df_counts"].head())

M. Gérald Darmanin - Moyenne/semaine (occurrences) : 1056.50
M. Gérald Darmanin - Médiane/semaine (occurrences) : 897.5
M. Gérald Darmanin - Moyenne/semaine (proportion)  : 0.07
M. Gérald Darmanin - Médiane/semaine (proportion)  : 0.07
  periode  total_mentions  true_mentions  proportion_true
0    2017            1727             20         0.011581
1    2018            1969             36         0.018283
2    2019             974             23         0.023614
3    2020             806             76         0.094293
4    2021             821            149         0.181486

## Personnel politique par groupes

In [44]:
# Fonction générale 

# Définir la personne recherchée 
parti = "LR"

# Filtrer sur le parti choisi
df_partis = df[df["parti_affiliation"] == parti]

# Compter le nombre de fois où chaque orateur dit "République"
counts = (
    df_partis.groupby("nom_orateur")["repu_match_valide"]
    .agg(total_mentions="count", true_mentions=lambda x: (x == True).sum())
    .reset_index()
)

# Calcul de la proportion
counts["proportion_true"] = counts["true_mentions"] / counts["total_mentions"]

# Filtrer les orateurs avec au moins 10 mentions True
filtered = counts[counts["true_mentions"] >= 10]

# Trier par proportion décroissante et garder les 10 premiers
df_top10_partis = filtered.sort_values("proportion_true", ascending=False).head(10).reset_index(drop=True)

# Figure
fig_top_orateurs_partis = px.bar(
   df_top10_partis,
    x="nom_orateur_clean",
    y="proportion_true",
    title=f"Top 10 des député.es {parti} en proportions des mentions de la 'République'",
    labels={"nom_orateur_clean": "Député.es", "proportion_true": "% 'République'"},
    template="plotly_white",
)
fig_top_orateurs_partis.update_layout(
    xaxis_tickangle=-45,
    showlegend=False,
)
fig_top_orateurs_partis.show()

df_top10_partis

KeyError: 'parti_affiliation'

#### tentative en cours d'avoir des stats plus fines par partis.

In [ ]:
# Définir la personne recherchée 
parti = "LFI"

# Filtrer sur le parti choisi
df_partis = df[df["parti_affiliation"] == parti]

def top_orateurs_partis_periodique(df_partis, periode="annee", annee=None, semaine=None, jour=None, 
                            date_debut=None, date_fin=None, jours=None,
                            colonne_condition="repu_match_valide",
                            seuil_min_true=None, top_n=20):

    # --- Filtrage selon la période ---
    if periode == "annee":
        if annee is None:
            raise ValueError("Il faut préciser l'année pour periode='annee'")
        df_filtered = df[df["dateSeance_day"].dt.year == annee]
        titre = f"Personnel politique mobilisant en % le plus la 'République' en {annee} à l'Assemblée Nationale (Seuil de {seuil_min_true} occurences)"

    elif periode == "semaine":
        if annee is None or semaine is None:
            raise ValueError("Il faut préciser l'année et la semaine pour periode='semaine'")
        df_filtered = df[
            (df["dateSeance_day"].dt.isocalendar().year == annee) &
            (df["dateSeance_day"].dt.isocalendar().week == semaine)
        ]
        titre = f"Personnel politique mobilisant en % le plus la 'République' la {semaine} semaine {annee} à l'Assemblée Nationale (Seuil de {seuil_min_true})"

    elif periode == "jour":
        if jour is None:
            raise ValueError("Il faut préciser la date pour periode='jour'")
        jour_dt = pd.to_datetime(jour).date()
        df_filtered = df[df["dateSeance_day"].dt.date == jour_dt]
        titre = f"Personnel politique mobilisant le plus en % la 'République' le {jour_dt} (Seuil de {seuil_min_true} occurences)"

    elif periode == "intervalle":
        if date_debut is None or date_fin is None:
            raise ValueError("Il faut préciser date_debut et date_fin pour periode='intervalle'")
        debut = pd.to_datetime(date_debut)
        fin = pd.to_datetime(date_fin)
        df_filtered = df[(df["dateSeance_day"] >= debut) & (df["dateSeance_day"] <= fin)]
        titre = f"Personnel politique mobilisant le plus en % la 'République' du {debut.date()} au {fin.date()} (Seuil de {seuil_min_true} occurences)"

    elif periode == "jours":
        if jours is None or not isinstance(jours, (list, tuple)):
            raise ValueError("Il faut fournir une liste de dates pour periode='jours'")
        jours_dt = [pd.to_datetime(j).date() for j in jours]
        df_filtered = df[df["dateSeance_day"].dt.date.isin(jours_dt)]
        titre = f"Personnel politique mobilisant le plus la 'République' en % lors de X évènement (Seuil de {seuil_min_true} occurences)"

    else:
        raise ValueError("periode doit être 'annee', 'semaine', 'jour', 'intervalle' ou 'jours'")

    # --- Comptage des occurrences ---
    counts = (
        df_filtered.groupby("nom_orateur_clean")[colonne_condition]
        .agg(total_mentions="count", true_mentions=lambda x: (x == True).sum())
        .reset_index()
    )
    counts["proportion_true"] = counts["true_mentions"] / counts["total_mentions"]

    # --- Filtrage par seuil ---
    filtered = counts[counts["true_mentions"] >= seuil_min_true]

    # --- Trier par proportion décroissante et garder top_n ---
    df_top = (
        filtered.sort_values("proportion_true", ascending=False)
        .head(top_n)
        .reset_index(drop=True)
    )

    # --- Graphique ---
    fig = px.bar(
        df_top,
        x="nom_orateur_clean",
        y="proportion_true",
        hover_data=["true_mentions", "total_mentions"],
        title=titre,
        template="plotly_white",
    )
    fig.update_layout(xaxis_tickangle=-45, showlegend=False, yaxis_title="Proportion des interventions totales", xaxis_title="Personnel politique")
    fig.show()

    return df_top

In [ ]:
# Top 10 orateurs en % lors de la deuxième phase de discussion post débat Sénat 
top_orateurs_partis_periodique(df_partis, periode="jours", jours=["2021-06-28", "2021-06-29", "2021-06-30", "2021-07-01", "2021-01-23"], seuil_min_true=5)

## Autres variables

--> en réalité ce qui serait utile ce serait de faire des vraies stats/régressions pour mesurer le poids de chacune de ces variables sur la probabilité d'utiliser la république. À voir comment faire

In [ ]:
df["civ"] = df["civ"].replace({"M.": "Homme", "Mme": "Femme"})

In [ ]:
df.to_csv(
    "../data/interim/df_identification_republi_simple.csv",
    index=False,
)

In [ ]:
fig = px.bar(df["civ"].value_counts())
fig.update_layout(
    title="Répartition des genres (civ)", template="plotly_white", showlegend=False
)
fig.show()

### Autres variables

In [ ]:
# Nécessité ici de transformer l'âge en chiffre pour l'ordonner. 

# Compter le nombre de fois où chaque orateur dit "République"
counts = (
    df.groupby("experienceDepute")["repu_match_valide"]
    .agg(total_mentions="count", true_mentions=lambda x: (x == True).sum())
    .reset_index()
)

# Calcul de la proportion
counts["proportion_true"] = counts["true_mentions"] / counts["total_mentions"]

# Filtrer les orateurs avec au moins 10 mentions True
filtered = counts[counts["true_mentions"] >= 50]

# Trier par proportion décroissante et garder les 40 premiers
df_experience_top20 = filtered.sort_values("proportion_true", ascending=False).head(40).reset_index(drop=True)

df_experience_top20

# Graphique
fig_experience = px.bar(
    df_experience_top20,
    x="experienceDepute",
    y="proportion_true",
    title="Évolution de la proportion d'utilisation de la 'République avec l'expérience",
    labels={"experienceDepute": "Expérience", "proportion_true": "% 'République'"},
    template="plotly_white",
)

fig_experience.update_layout(xaxis_tickangle=-45)

fig_experience.show()

df_experience_top20

In [ ]:
# Compter le nombre de fois où chaque orateur dit "République"
counts = (
    df.groupby("age")["repu_match_valide"]
    .agg(total_mentions="count", true_mentions=lambda x: (x == True).sum())
    .reset_index()
)

# Calcul de la proportion
counts["proportion_true"] = counts["true_mentions"] / counts["total_mentions"]

# Filtrer les orateurs avec au moins 10 mentions True
filtered = counts[counts["true_mentions"] >= 50]

# Trier par proportion décroissante et garder les 40 premiers
df_experienceb_top20 = filtered.sort_values("proportion_true", ascending=False).head(40).reset_index(drop=True)

# Graphique
fig_experienceb = px.bar(
    df_experienceb_top20,
    x="age",
    y="proportion_true",
    title="Évolution de la proportion d'utilisation de la 'République avec l'âge",
    labels={"age": "Age", "proportion_true": "% 'République'"},
    template="plotly_white",
)

fig_experienceb.update_layout(xaxis_tickangle=-45)

fig_experienceb.show()

df_experienceb_top20

In [ ]:
# Compter le nombre de fois où chaque orateur d'un département dit "République"
counts = (
    df.groupby("departementCode")["repu_match_valide"]
    .agg(total_mentions="count", true_mentions=lambda x: (x == True).sum())
    .reset_index()
)

# Calcul de la proportion
counts["proportion_true"] = counts["true_mentions"] / counts["total_mentions"]

# Filtrer les orateurs avec au moins 10 mentions True
filtered = counts[counts["true_mentions"] >= 50]

# Trier par proportion décroissante et garder les 40 premiers
df_dpt_top20 = filtered.sort_values("proportion_true", ascending=False).head(40).reset_index(drop=True)

df_dpt_top20

# Graphique
fig_dpt = px.bar(
    df_dpt_top20,
    x="departementCode",
    y="proportion_true",
    title="Évolution de la proportion d'utilisation de la 'République par département",
    labels={"departementCode": "Departement", "proportion_true": "% 'République'"},
    template="plotly_white",
)

fig_dpt.update_layout(xaxis_tickangle=-45)

fig_dpt.show()

df_dpt_top20

==> en VA ce sont les départements IDF et surtout le 93 de LFI qui reviennent le plus, mais en % ce sont les territoires d'outre-mers

In [ ]:
# Compter le nombre de fois où chaque orateur/genre dit "République"
counts = (
    df.groupby("civ")["repu_match_valide"]
    .agg(total_mentions="count", true_mentions=lambda x: (x == True).sum())
    .reset_index()
)

# Calcul de la proportion
counts["proportion_true"] = counts["true_mentions"] / counts["total_mentions"]

# Filtrer les orateurs avec au moins 10 mentions True
filtered = counts[counts["true_mentions"] >= 50]

# Trier par proportion décroissante et garder les 40 premiers
df_genre_top20 = filtered.sort_values("proportion_true", ascending=False).head(40).reset_index(drop=True)

df_genre_top20

## Test de régressions linéaires

### Étape 1 : restructuration des variables

In [ ]:
# Réfléchir à recoder l'âge en génération (reprendre celles de VT ?)

In [ ]:
df["genre"] = df["civ"].replace({"Homme": "1", "Femme": "0"})

In [ ]:
df["repu"] = df["repu_match_valide"].replace({"True": "1", "False": "0"})

In [ ]:
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

def regression_lineaire(df, y_col, x_cols):
  
    # Définir X et y
    X = df[x_cols]
    y = df[y_col]
    
    # Encoder les colonnes catégorielles si nécessaire
    X = pd.get_dummies(X, drop_first=True)
    
    # Forcer en 2D si une seule variable explicative
    if X.shape[1] == 1:
        X = X.values.reshape(-1, 1)
    else:
        X = X.values
    
    # y doit être 1D
    y = y.values
    
    # Créer et entraîner le modèle
    model = LinearRegression()
    model.fit(X, y)
    
    # Prédictions
    y_pred = model.predict(X)
    
    # Résultats
    print("Coefficient(s):", model.coef_)
    print("Intercept:", model.intercept_)
    print("Score R²:", model.score(X, y))
    
    # Graphique si une seule variable explicative
    if X.shape[1] == 1:
        plt.scatter(X, y, color="blue", label="Données réelles")
        plt.plot(X, y_pred, color="red", label="Régression")
        plt.xlabel(x_cols[0])
        plt.ylabel(y_col)
        plt.legend()
        plt.show()
    
    return model

In [ ]:
modele = regression_lineaire(df, y_col="repu_match_valide", x_cols=["parti_affiliation"])

In [ ]:
modele = regression_lineaire(df, y_col="repu_match_valide", x_cols=["experienceDepute"])

In [ ]:
modele = regression_lineaire(df, y_col="repu_match_valide", x_cols=["parti_affiliation", "civ", "experienceDepute"])

In [ ]:
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm

def regression_lineaire_df(df, y_col, x_cols, summary=False):
 
    # Définir X (variable à expliquer) et y (variable explicatives)
    X = df[x_cols]
    y = df[y_col]
    
    # Encoder les colonnes catégorielles si nécessaire
    X = pd.get_dummies(X, drop_first=True)
    
    # Forcer en numpy array
    X_values = X.values
    y_values = y.values
    
    # ----- Version scikit-learn -----
    model = LinearRegression()
    model.fit(X_values, y_values)
    y_pred = model.predict(X_values)
    
    print("Régression (scikit-learn)")
    print("Coefficient(s):", model.coef_)
    print("Intercept:", model.intercept_)
    print("Score R²:", model.score(X_values, y_values))
    
    # Graphique si une seule variable explicative
    if X.shape[1] == 1:
        plt.scatter(X_values, y_values, color="blue", label="Données réelles")
        plt.plot(X_values, y_pred, color="red", label="Régression")
        plt.xlabel(x_cols[0])
        plt.ylabel(y_col)
        plt.legend()
        plt.show()
    
    # ----- Version statsmodels -----
    if summary:
        X_sm = sm.add_constant(X)  # ajoute la constante pour l'intercept
        model_sm = sm.OLS(y, X_sm).fit()
        print("Résumé statistique (statsmodels):")
        print(model_sm.summary())
        return model, model_sm
    
    return model

In [ ]:
modele_sklearn, modele_stats = regression_lineaire_df(df, y_col="repu_match_valide", x_cols=["parti_affiliation", "civ"], summary=True)